### ISSUE TITLE
关于解析[]byte类型

### ISSUE THREAD

**Issue by liuxp0827** [json-iterator/go#1]
type TorrentInfo struct {
	InfoHash     []byte      `json:"InfoHash"`     
	InfoHashstr  string     `json:"InfoHashstr"`  
	AnnounceList []string `json:"AnnounceList"` 
	Length       int64        `json:"Length"`       
	PieceSize    int64        `json:"PieceSize"`    
	PieceNum     int64     `json:"PieceNum"`     
}

请问下,像InfoHash这种[]byte类型要如何解析,使用ReadStringAsBytes 不是我要的结果

**Comment by taowen** [comment]
是要支持base64读取是吧，这个还要开发一下，目前不支持。ReadStringAsBytes应该作为private的，只是省去了string构造的加速方法而已。

**Comment by taowen** [comment]
```
func Test_reflect_base64(t *testing.T) {
	iter := ParseString(`"YWJj"`)
	val := []byte{}
	RegisterTypeDecoder("[]uint8", func(ptr unsafe.Pointer, iter *Iterator) {
		*((*[]byte)(ptr)) = iter.ReadBase64()
	})
	defer ClearDecoders()
	iter.Read(&val)
	if "abc" != string(val) {
		t.Fatal(string(val))
	}
}
```

现在已经支持了

**Comment by liuxp0827** [comment]
thx
