### ISSUE TITLE
func type not ignored on json:"-"

### ISSUE THREAD

**Issue by javierprovecho** [json-iterator/go#120]
Hi,

while implementing [json-iterator/go](https://github.com/json-iterator/go) on [gin-gonic/gin](https://github.com/gin-gonic/gin/) we discovered an error (https://github.com/gin-gonic/gin/issues/991)

The following example does not match the standard `encoding/json` lib:

```go
package main

import json1 "encoding/json"
import json2 "github.com/json-iterator/go"
import "fmt"

type test struct {
	Msg            string `json:"message"`
	NotVisible     string `json:"-"`
	FuncNotVisible func() `json:"-"`
}

func main() {
	result1, err1 := json1.Marshal(&test{Msg: "hello", NotVisible: "world", FuncNotVisible: func() {}})
	fmt.Println(string(result1), err1)

	result2, err2 := json2.Marshal(&test{Msg: "hello", NotVisible: "world", FuncNotVisible: func() {}})
	fmt.Println(string(result2), err2)
}
```

I suppose it parses the type before the flags on a supposedly discarded variable with json:"-"

**Comment by appleboy** [comment]
I can confirm this issue.

**Comment by mtfelian** [comment]
I also confirm.

**Comment by taowen** [comment]
thanks, pr merged
