### ISSUE TITLE
map decode not as expect

### ISSUE THREAD

**Issue by robscc** [json-iterator/go#129]
here is the code
```go
package main

import (
	"fmt"
	"strings"

	"github.com/json-iterator/go"
)

func main() {
	json := jsoniter.ConfigCompatibleWithStandardLibrary
	reader := strings.NewReader(`{"branch":"beta","change_log":"add the rows{10}","channel":"fros","create_time":"2017-06-13 16:39:08","firmware_list":"","md5":"80dee2bf7305bcf179582088e29fd7b9","note":{"CoreServices":{"md5":"d26975c0a8c7369f70ed699f2855cc2e","package_name":"CoreServices","version_code":"76","version_name":"1.0.76"},"FrDaemon":{"md5":"6b1f0626673200bc2157422cd2103f5d","package_name":"FrDaemon","version_code":"390","version_name":"1.0.390"},"FrGallery":{"md5":"90d767f0f31bcd3c1d27281ec979ba65","package_name":"FrGallery","version_code":"349","version_name":"1.0.349"},"FrLocal":{"md5":"f15a215b2c070a80a01f07bde4f219eb","package_name":"FrLocal","version_code":"791","version_name":"1.0.791"}},"pack_region_urls":{"CN":"https://s3.cn-north-1.amazonaws.com.cn/xxx-os/ttt_xxx_android_1.5.3.344.393.zip","default":"http://192.168.8.78/ttt_xxx_android_1.5.3.344.393.zip","local":"http://192.168.8.78/ttt_xxx_android_1.5.3.344.393.zip"},"pack_version":"1.5.3.344.393","pack_version_code":393,"region":"all","release_flag":0,"revision":62,"size":38966875,"status":3}`)
	decoder := json.NewDecoder(reader)
	params := make(map[string]interface{})
	err := decoder.Decode(&params)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Printf("%+v\n", params)
	}
}
```

it would output this
`
map[branch:beta create_time:2017-06-13 16:39:08 firmware_list: note:map[ack_region_u:<nil> /192.168:<nil> ack_versi:map[version_code:349 ze":38966875:<nil> "1.:<nil> region":"all:<nil>] FrLocal:map[version_name:1.0.791 md5:f15a215b2c070a80a01f07bde4f219eb package_name:FrLocal version_code:791]] revision:62 change_log:add the rows{10} channel:fros pack_region_urls:map[default:http://192.168.8.78/ttt_xxx_android_1.5.3.344.393.zip local:http://192.168.8.78/ttt_frospack_android_1.5.3.344.393.zip CN:https://s3.cn-north-1.amazonaws.com.cn/xxx-os/ttt_xxx_android_1.5.3.344.393.zip region:all md5:80dee2bf7305bcf179582088e29fd7b9 pack_version:1.5.3.344.393 pack_version_code:393 size:3.8966875e+07 status:3 release_flag:0]
`
what is <b>not i expect</b>.

but when i use origin <b>"encoding/json"</b>

it would output this
`
map[change_log:add the rows{10} note:map[CoreServices:map[md5:d26975c0a8c7369f70ed699f2855cc2e package_name:CoreServices version_code:76 version_name:1.0.76] FrDaemon:map[package_name:FrDaemon version_code:390 version_name:1.0.390 md5:6b1f0626673200bc2157422cd2103f5d] FrGallery:map[version_code:349 version_name:1.0.349 md5:90d767f0f31bcd3c1d27281ec979ba65 package_name:FrGallery] FrLocal:map[md5:f15a215b2c070a80a01f07bde4f219eb package_name:FrLocal version_code:791 version_name:1.0.791]] pack_region_urls:map[CN:https://s3.cn-north-1.amazonaws.com.cn/xxx-os/ttt_xxx_android_1.5.3.344.393.zip default:http://192.168.8.78/ttt_xxx_android_1.5.3.344.393.zip local:http://192.168.8.78/ttt_xxx_android_1.5.3.344.393.zip] pack_version:1.5.3.344.393 channel:fros md5:80dee2bf7305bcf179582088e29fd7b9 region:all status:3 size:3.8966875e+07 branch:beta firmware_list: release_flag:0 revision:62 create_time:2017-06-13 16:39:08 pack_version_code:393]
`

here is the origin code
```go
package main

import (
	"fmt"
	"strings"

	//jsoniter "github.com/json-iterator/go"
	"encoding/json"
)

func main() {
	//json := jsoniter.ConfigCompatibleWithStandardLibrary
	reader := strings.NewReader(`{"branch":"beta","change_log":"add the rows{10}","channel":"fros","create_time":"2017-06-13 16:39:08","firmware_list":"","md5":"80dee2bf7305bcf179582088e29fd7b9","note":{"CoreServices":{"md5":"d26975c0a8c7369f70ed699f2855cc2e","package_name":"CoreServices","version_code":"76","version_name":"1.0.76"},"FrDaemon":{"md5":"6b1f0626673200bc2157422cd2103f5d","package_name":"FrDaemon","version_code":"390","version_name":"1.0.390"},"FrGallery":{"md5":"90d767f0f31bcd3c1d27281ec979ba65","package_name":"FrGallery","version_code":"349","version_name":"1.0.349"},"FrLocal":{"md5":"f15a215b2c070a80a01f07bde4f219eb","package_name":"FrLocal","version_code":"791","version_name":"1.0.791"}},"pack_region_urls":{"CN":"https://s3.cn-north-1.amazonaws.com.cn/xxx-os/ttt_xxx_android_1.5.3.344.393.zip","default":"http://192.168.8.78/ttt_xxx_android_1.5.3.344.393.zip","local":"http://192.168.8.78/ttt_xxx_android_1.5.3.344.393.zip"},"pack_version":"1.5.3.344.393","pack_version_code":393,"region":"all","release_flag":0,"revision":62,"size":38966875,"status":3}`)
	decoder := json.NewDecoder(reader)
	params := make(map[string]interface{})
	err := decoder.Decode(&params)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Printf("%+v\n", params)
	}
}
```

any sugguesion on this?

**Comment by taowen** [comment]
It is bug, should be fixed

**Comment by taowen** [comment]
fixed
