### ISSUE TITLE
Failed parsing input: parser: bad import "unsafe" 

### ISSUE THREAD

**Issue by ankemp** [json-iterator/go#132]
This package is used in: https://github.com/gin-gonic/gin which supposedly can play nice with Google app engine.

But when try to run my GO app through the local app engine emulator, I'm getting this error during build:
`go-app-builder: Failed parsing input: parser: bad import "unsafe" in github.com/json-iterator/go/feature_adapter.go from GOPATH`

Any idea why this could be happening?

**Comment by taowen** [comment]
maybe GAE does not allow using `unsafe.Pointer`

**Comment by taowen** [comment]
gin added build tag `-tags=jsoniter`
