### ISSUE TITLE
Bad input does not cause an error when it should

### ISSUE THREAD

**Issue by thockin** [json-iterator/go#133]
I have a test coming for this, but for example:

```
$ go test . -run RandomInput
--- FAIL: Test_RandomInput_Bytes (0.00s)
	unmarshal_input_test.go:69: Expected error unmarshaling as struct:
		as string: "6\x8d\x1e"
		as bytes: [54 141 30]
--- FAIL: Test_RandomInput_String (0.00s)
	unmarshal_input_test.go:69: Expected error unmarshaling as struct:
		as string: "6遆逜x<ɪ+鑴eƹ)嫳钫j蒶X"
		as bytes: [54 233 129 134 233 128 156 120 60 201 170 43 233 145 180 101 198 185 41 229 171 179 233 146 171 106 232 146 182 88]
FAIL
```

**Comment by taowen** [comment]
Has fixed the easy cases. The more difficult one is to skip `{abc}`. Currently, skip does not validate anything between `{` and `}`. Will need to write a new implementation of `Skip()` to do the validation. The old implementation will be enabled by build tags.

**Comment by thockin** [comment]
I am seeing things like:
```
--- FAIL: Test_RandomInput_Bytes (0.03s)
	unmarshal_input_test.go:71: Expected error unmarshaling as struct:
		as string: "{K\xf7\xd8\x17Z\x03}"
		as bytes: [123 75 247 216 23 90 3 125]
```

...which (naively) should fail trying to extract the key name - not skip?  I don't know the internals very well - why is it trying to skip this?

**Comment by thockin** [comment]
Also, does that mean I should add a case for list parsing?  `[ ... ]` ?  Any other interesting cases that the parser might distinguish that this test doesn't exercise?

**Comment by thockin** [comment]
Also, I coded 10K loops, but honestly, being random, we should make that number as large as we think we can tolerate in a `go test`.

**Comment by taowen** [comment]
Yes, `{abc}` or `[abc]` is a problem. I am working on that.

**Comment by taowen** [comment]
should be fixed
