### ISSUE TITLE
this package can't unmarshal data into a long struct,but into a map

### ISSUE THREAD

**Issue by moshuipan** [json-iterator/go#141]
func testJson() {
	//	a := struct {
	//		Ret_code    string
	//		Ret_msg     string
	//		Token       string
	//		Sign        string
	//		Sign_type   string
	//		Oid_partner string
	//		No_order    string
	//		Dt_order    string
	//		Money_order string
	//		Oid_paybill string
	//		Sms_flag    string
	//		Result_pay  string
	//		Info_order  string
	//		No_agree    string
	//	}{}
	a := make(map[string]string)
	body := `{"dt_order":"1234567890","money_order":"100","no_order":"TEST12345678901234567890","oid_partner":"1234567890123","oid_paybill":"1234567890123","ret_code":"1234","ret_msg":"交易成功","sign":"1234567890","sign_type":"11s","sms_flag":"1","token":"1234567890"}`
	err := njson.Unmarshal([]byte(body), &a)
	fmt.Println(a, err, len(a))
}

**Comment by taowen** [comment]
what is the error?

**Comment by moshuipan** [comment]
err=nil

**Comment by taowen** [comment]
#142 同一个问题？ @moshuipan

**Comment by taowen** [comment]
duplicate with #142
