### ISSUE TITLE
使用itertator,部分json数据丢失

### ISSUE THREAD

**Issue by antyiwei** [json-iterator/go#142]
json 过长，就会出现，生产中得到的教训

**Comment by taowen** [comment]
请给一下测试数据和struct定义

**Comment by antyiwei** [comment]
{"dt_order":"1234567890","money_order":"100","no_order":"TEST12345678901234567890","oid_partner":"1234567890123","oid_paybill":"1234567890123","ret_code":"1234","ret_msg":"交易成功","sign":"1234567890","sign_type":"11s","sms_flag":"1","token":"1234567890"}

**Comment by antyiwei** [comment]
package main

import (
	"encoding/json"
	"fmt"

	jsoniter "github.com/json-iterator/go"
)

func main() {
	testJson()
}

func testJson() {
	a := struct {
		Ret_code    string
		Ret_msg     string
		Token       string
		Sign        string
		Sign_type   string
		Oid_partner string
		No_order    string
		Dt_order    string
		Money_order string
		Oid_paybill string
		Sms_flag    string
		Result_pay  string
		Info_order  string
		No_agree    string
	}{}
	// a := make(map[string]string)

	// jsoniter
	body := `{"dt_order":"1234567890","money_order":"100","no_order":"TEST12345678901234567890","oid_partner":"1234567890123","oid_paybill":"1234567890123","ret_code":"1234","ret_msg":"交易成功","sign":"1234567890","sign_type":"11s","sms_flag":"1","token":"1234567890"}`
	err := jsoniter.Unmarshal([]byte(body), &a)
	fmt.Println(a, err)

	// go json
	err2 := json.Unmarshal([]byte(body), &a)
	fmt.Println(a, err2)
}

**Comment by antyiwei** [comment]
a := struct {
		Ret_code    string `json:"ret_code"`
		Ret_msg     string `json:"ret_msg"`
		Token       string `json:"token"`
		Sign        string `json:"sign"`
		Sign_type   string `json:"sign_type"`
		Oid_partner string `json:"oid_partner"`
		No_order    string `json:"no_order"`
		Dt_order    string `json:"dt_order"`
		Money_order string `json:"money_order"`
		Oid_paybill string `json:"oid_paybill"`
		Sms_flag    string `json:"sms_flag"`
		Result_pay  string `json:"result_pay"`
		Info_order  string `json:"info_order"`
		No_agree    string `json:"no_agree"`
	}{}
	// 可以

**Comment by taowen** [comment]
```
{1234 交易成功 1234567890 1234567890 11s 1234567890123 TEST12345678901234567890 1234567890 100 1234567890123 1   } <nil>
{1234 交易成功 1234567890 1234567890 11s 1234567890123 TEST12345678901234567890 1234567890 100 1234567890123 1   } <nil>
```

There is no difference on my local environment. Are you using the latest master branch? In older version, the field is case sensitive. It was fixed for some time now.

**Comment by antyiwei** [comment]
是最新mast 分支

**Comment by taowen** [comment]
是大小写问题吗？我这复现不了哇

**Comment by moshuipan** [comment]
是这样的，我的结构体里有冗余的字段，但是json数据里并没有这样的字段，使用golang原生包可以解析已有已有字段的数据，但是使用jsoniter则解析不到已有字段数据

**Comment by taowen** [comment]
按照 @antyiwei 给的测试代码，我这里跑出来的结果，标准库和jsoniter是一样的行为啊。你给个其他的代码样例？冗余字段怎么理解？

**Comment by moshuipan** [comment]
结构体里的有几个字段是多余的如No_agree 、Info_order

**Comment by taowen** [comment]
ok, I reproduced the problem

**Comment by moshuipan** [comment]
:+1: 是什么问题？ @taowen

**Comment by taowen** [comment]
应该修复了。之前改大小问题的时候漏掉了一个代码路径。

**Comment by guoyucheng** [comment]
hi 同样遇到丢数据的情况
type Image struct {
	Id               string                   `json:"id"`
	Title            string                   `json:"title"`
	Channels         string                   `json:"channels"`
	tags             []string                 `json:"tags"`
	CreateTime       int64                    `json:"create_time"`
	LastModifiedTime int64                    `json:"last_modified_time"`
	Desc             string                   `json:"description"`
	Cp               string                   `json:"cp"`
	TopicList        []map[string]interface{} `json:"topic_list"`
	ChannelIds       []string                 `json:"channel_ids"`
	TagIds           []string                 `json:"tag_ids"`
	IsRecommend      int64                    `json:"isrecommend"`
	BeginTime        int64                    `json:"begin_t"`
	EndTime          int64                    `json:"end_t"`
	Count            map[string]int64         `json:"count"`
	DailyCount       map[string]int64         `json:"dailyCount"`
	Level            int64                    `json:"level"`
}

x := `{
	"__isset_bit_vector": [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
	"begin_t": 1512366936,
	"channel_ids": ["CC00000009"],
	"channels": ["美食"],
	"count": {
		"buy": 237,
		"click": 3261,
		"expose": 240344,
		"like": 799,
		"refresh": 23,
		"share": 21,
		"uncollection": 130,
		"unlike": 413,
		"view": 16589
	},
	"cp": "xxxx",
	"cp_id": "CP01000001",
	"create_time": 1512366997,
	"dailyCount": {
		"click": 16,
		"expose": 1021,
		"like": 5,
		"unlike": 1,
		"view": 65
	},
	"description": "选好甜食搭档平日里，我们吃甜食可以吃些热量较低的点心，比如吃全麦面包加水果就是好选择，全麦纤维和水果纤维都是能保持好身材的，微量的糖不会导致发胖，况且吃面包后喝水也影响了胃部的消化，避免脂肪的沉积。@视觉中国",
	"end_t": 1559318400,
	"favor_count": 0,
	"id": "I01041323",
	"isrecommend": 0,
	"last_modified_time": 1544705432,
	"level": 0,
	"media": "MI食尚",
	"media_id": "ME01000091",
	"payload_size": 0,
	"status": 0,
	"status_t": 10,
	"subscribe_count": 0,
	"subtitle": "",
	"tag_ids": ["TAG01000042", "TAG01000071", "TAG01000548", "TAG01000657", "TAG01001556"],
	"tags": ["蛋糕", "甜美", "甜品", "紫色调", "点心"],
	"title": "甜品是好身材的天敌？",
	"topic_list": [{
		"id": "T01041324",
		"pos": 0
	}],
	"url": "xxxxxx",
	"vendor_id": "V00000001",
	"weight": 0
}`
var imageObjt image.Image
var json1 = jsoniter.ConfigCompatibleWithStandardLibrary
json1.Unmarshal([]byte(x), &imageObjt)
fmt.Println(">>>>>:", imageObjt)
{   [] 0 0   [] [CC00000009] [] 0 1512366936 0 map[] map[] 0}
缺少很多字段，用官方的和ffjson就是没问题的

@taowen

**Comment by taowen** [comment]
there is a error in your input. using the std json, there is also a error returned:
`json: cannot unmarshal array into Go struct field Image.channels of type string`

**Comment by guoyucheng** [comment]
@taowen get，but why ffjson can unmarshal
