### ISSUE TITLE
compatibility with encoding/json

### ISSUE THREAD

**Issue by dsabonis** [json-iterator/go#144]
Found out a case where jsoniter is unable to unmarshal a type while `encoding/json` works fine. I'm trying to use jsoniter with [this](https://github.com/bsm/openrtb) openrtb lib.

Here's a snippet where it fails:
```
package main

import (
	"fmt"
	"github.com/json-iterator/go"
	"log"
	"encoding/json"
)

type Extension []byte

// UnmarshalJSON sets *e to a copy of data.
func (e *Extension) UnmarshalJSON(data []byte) error {
	fmt.Println("UnmarshalJSON()")
	*e = append((*e)[0:0], data...)
	return nil
}

func main() {
	ext := Extension(`{"key": "val"}`)

        // json works fine here
	if err := json.Unmarshal([]byte(`{"key": "val"}`), &ext); err != nil {
		log.Fatalf("json error: %v", err)
	}

        // jsoniter fails
	if err := jsoniter.ConfigCompatibleWithStandardLibrary.Unmarshal([]byte(`{"key": "val"}`), &ext); err != nil {
		log.Fatalf("jsoninter error: %v", err)
	}

}
```

Error:
```2017/08/07 21:32:53 jsoninter error: main.Extension: ReadArray: expect [ or , or ] or n, but found: {, parsing 1 ...{... at {"key": "val"}```

Noticed that when using jsoniter `UnmarshalJSON` method is not called (due to pointer receiver?)
`UnmarshalJSON` is called successfully when using `encoding/json`.

Any ideas why jsoniter and `encoding/json` behave differently here?

**Comment by taowen** [comment]
should be fixed
