### ISSUE TITLE
Support custom struct field tag name in marshal?

### ISSUE THREAD

**Issue by davyxu** [json-iterator/go#146]
Like:

type UserProfile struct{

       OnlineData int   `mem: onlinedata`  // this field is memory data, also use json
       DBData int   `db: onlinedata`
}

json.Marshal( &UserProfile{ ... some data },   "mem"  )    // use mem tag to marshal
json.Marshal( &UserProfile{ ... some data },   "db"  )    // use db tag to marshal

**Comment by taowen** [comment]
Is anyone else vote for this feature?

**Comment by taowen** [comment]
implemented
