### ISSUE TITLE
Get Structure?

### ISSUE THREAD

**Issue by suntong** [json-iterator/go#148]
Would it be possible to use the parser to get the JSON's Structure?

I saw there are a bunch of Extensions including the  `UpdateStructDescriptor` one. Could they be used to get the JSON's Structure? 

Thx!

**Comment by taowen** [comment]
https://mholt.github.io/json-to-go/

**Comment by suntong** [comment]
Yeah, I know it and I actually also know the code behind it. 

I was asking whether this project has any plan or capability to get the JSON's Structure -- "no" can be an answer. :)

**Comment by taowen** [comment]
there is no such plan
