### ISSUE TITLE
Iterator.ReadInt() need a error

### ISSUE THREAD

**Issue by xfort** [json-iterator/go#15]
Iterator.ReadInt() , 如果数据不是数字，现在会返回默认值0。无法判断是解析成功的结果，还是解析失败的结果。我觉得解析返回数据的方法都需要一个error，用来标记是否解析成功。

**Comment by taowen** [comment]
Iterator 上有一个 Error 字段，代表 last error。你可以解析完之后用这个 Error 字段来判断是否成功。

**Comment by xfort** [comment]
Thanks！
我认为在方法后直接返回error 更加符合golang，也更方便判断。下面是修改后的代码，仅供参考
`func (iter *Iterator) ReadInt64() (ret int64,error) {
	c := iter.nextToken()
	if c == '-' {
		val := iter.readUint64(iter.readByte())
		if val > int64Max + 1 {
			iter.reportError("ReadInt64", "overflow: " + strconv.FormatUint(uint64(val), 10))
			return 0,errors.New("ReadInt64", "overflow: " + strconv.FormatUint(uint64(val), 10))
		}
		return -int64(val),nil
	} else {
		val := iter.readUint64(c)
		if val > int64Max {
			iter.reportError("ReadInt64", "overflow: " + strconv.FormatUint(uint64(val), 10))
			return 0,errors.New("ReadInt64", "overflow: " + strconv.FormatUint(uint64(val), 10))
		}
		return int64(val),nil
	}
}
`

**Comment by xfort** [comment]
`func (iter *Iterator) ReadInt64() (ret int64,error) {
	c := iter.nextToken()
	if c == '-' {
		val := iter.readUint64(iter.readByte())
		if val > int64Max + 1 {
			iter.reportError("ReadInt64", "overflow: " + strconv.FormatUint(uint64(val), 10))
			return 0,errors.New("ReadInt64", "overflow: " + strconv.FormatUint(uint64(val), 10))
		}
		return -int64(val),nil
	} else {
		val := iter.readUint64(c)
		if val > int64Max {
			iter.reportError("ReadInt64", "overflow: " + strconv.FormatUint(uint64(val), 10))
			return 0,errors.New("ReadInt64", "overflow: " + strconv.FormatUint(uint64(val), 10))
		}
		return int64(val),nil
	}
}
`

**Comment by taowen** [comment]
我知道这样更golang。但是每一个read都返回error的话，使用起来太麻烦了。一般我就是在处理的最后面判断一下整个过程里error是不是nil就好了。
