### ISSUE TITLE
omitempty not working as expected on hashmap and nested struct

### ISSUE THREAD

**Issue by klaubert** [json-iterator/go#151]
In some situation an empty content of struct still produce a json (empty{}) content when I marshal it (jsoniter.Marshal(var))

```
Cookies       map[string]string   `json:"headers_cookies,omitempty"`
Sanitized     struct {
	Args            []string `json:"args,omitempty"`
	RequestHeaders  []string `json:"request_headers,omitempty"`
	ResponseHeaders []string `json:"response_headers,omitempty"`
} `json:"sanitized, omitempty"`
```
In my understanding, both example above must not produce any content. When using encoding/json "Cookie" is not part of the output, sadly the "Sanitezed" is.

Any chance to change to honor the omitempty in both cases?

best regards,

**Comment by taowen** [comment]
```go
import "encoding/json"

	type TestObject struct {
		Cookies       map[string]string   `json:"headers_cookies,omitempty"`
		Sanitized     struct {
			Args            []string `json:"args,omitempty"`
			RequestHeaders  []string `json:"request_headers,omitempty"`
			ResponseHeaders []string `json:"response_headers,omitempty"`
		} `json:"sanitized, omitempty"`
	}
	bytes, _ := json.Marshal(TestObject{})
	fmt.Println(string(bytes))
```
the standard library will output
```
{"sanitized":{}}
```

jsoniter will keep the behavior same as standard library.

**Comment by klaubert** [comment]
Ok, but and about the ```Cookies       map[string]string   `json:"headers_cookies,omitempty"```? Will keeping output?

**Comment by taowen** [comment]
the behavior should be same as standard library
