### ISSUE TITLE
ETA for a "stable" release tag?

### ISSUE THREAD

**Issue by thockin** [json-iterator/go#154]

**Comment by taowen** [comment]
how about today？

**Comment by thockin** [comment]
I just re-vendored you at 36b14963da70d11297d313183d7e6388c8510e1e - if that became 1.0 it would be nice.  If not, I can re-vendor.  Hoping to get this into Kubernetes v1.8.

**Comment by taowen** [comment]
https://github.com/json-iterator/go/releases/tag/1.0.0
