### ISSUE TITLE
Support for json.MarshalIndent ?

### ISSUE THREAD

**Issue by javasgl** [json-iterator/go#155]
encoding/json support `MarshalIndent`,but `json-iterator` don`t supported.
```
import "encoding/json"
json.MarshalIndent()
```

**Comment by taowen** [comment]
https://github.com/json-iterator/go/blob/master/feature_adapter.go 

MarshalIdent is "supported": only marshal indent with empty space is supported.

**Comment by javasgl** [comment]
😅  sorry . use `go get -u` update package then i got the `MarshalIndent`
