### ISSUE TITLE
Bug with FuzzyDecoders

### ISSUE THREAD

**Issue by 1stborn** [json-iterator/go#158]
ReadMapCB: expect { or n, parsing 24 ...aders":{"f... at {"id":3160,"headers":{ .......

type Email struct {
	Id uint64

	Encoding gomail.Encoding
	Charset  string

	Headers     map[string]utility.StringArray
	Body        EmailBody
	Alternative []EmailBody
	Attachment  map[string]EmailBody

	UserData map[string]interface{} `json:"user_data"`
}

It always stuck at reading Id, and if I put "id" at the end of JSON i got EOF

**Comment by taowen** [comment]
can you provide a sample json input?

**Comment by 1stborn** [comment]
Email: UserData: ReadMapCB: expect { or n, parsing 26 ..._data":{"s... at {"id":3163,"user_data":{"split":0,"type":5}}

**Comment by 1stborn** [comment]
Duplicate for https://github.com/json-iterator/go/issues/159

**Comment by cch123** [comment]
@1stborn , your issue is not the same with  mine.
The json string you provide 
```go
var text = []byte(`{"id":3163, somedata: null}`)
```
is not valid.
key in json is always string type, so the valid one should be
```
var text = []byte(`{"id":3163, "somedata": null}`)

```

**Comment by 1stborn** [comment]
just a typo, i change key here, if i remove extra.RegisterFuzzyDecoders() all work fine

**Comment by taowen** [comment]
@1stborn is it working now?
