### ISSUE TITLE
好像解析不了数据

### ISSUE THREAD

**Issue by emacsist** [json-iterator/go#17]
mac 下的 Golang 1.8 环境

`func BenchmarkHello2(b *testing.B) {
	rawString := `
	{"id":0,"bidId":"bid01492692440885","impId":"imp0","taskId":"1024","bidPrice":80,"winPrice":0,"isWon":0,"createTime":1492692440885,"updateTime":null,"device":"","age":30,"gender":"","location":"[中国, 山西, , ]","conType":"0","os":"iOS","osv":"","brand":"","geo":"","ip":"1.68.4.193","idfa":"","waxUserid":""}
	`
	var log bean.TaskBidLog
	hello.UnmarshalFromString(rawString, &log)
	b.Logf("%v\n", log.Age)
}`

用标准库里的就可以输出 30，但该库，一直没有成功。。。也没有见报错。。

**Comment by taowen** [comment]
```
type TaskBidLog struct {
	Age int
}

func Test2(t *testing.T) {
	rawString :=`
	{"id":0,"bidId":"bid01492692440885","impId":"imp0","taskId":"1024","bidPrice":80,"winPrice":0,"isWon":0,"createTime":1492692440885,"updateTime":null,"device":"","age":30,"gender":"","location":"[中国, 山西, , ]","conType":"0","os":"iOS","osv":"","brand":"","geo":"","ip":"1.68.4.193","idfa":"","waxUserid":""}`
	var log TaskBidLog
	err := UnmarshalFromString(rawString, &log)
	fmt.Println(err)
	fmt.Println(log.Age)
}
```

字符串的结尾可能是有换行。你先strip一下

**Comment by emacsist** [comment]
你好，不好意思，我的排版不好。但是 `log.Age` 正确的输出，它应该是 30 的，而不应该是 0 的呀，是不是？

**Comment by taowen** [comment]
噢，不对。这个应该是 Age 是大写，json里是小写的问题。

```
type TaskBidLog struct {
	age int
}

func Test2(t *testing.T) {
	rawString :=`
	{"id":0,"bidId":"bid01492692440885","impId":"imp0","taskId":"1024","bidPrice":80,"winPrice":0,"isWon":0,"createTime":1492692440885,"updateTime":null,"device":"","age":30,"gender":"","location":"[中国, 山西, , ]","conType":"0","os":"iOS","osv":"","brand":"","geo":"","ip":"1.68.4.193","idfa":"","waxUserid":""}`
	var log TaskBidLog
	err := UnmarshalFromString(rawString, &log)
	fmt.Println(err)
	fmt.Println(log.age)
}
```

这样就对了

```
<nil>
30
```

**Comment by emacsist** [comment]
噢，不好意思，我找到原因了。是因为我的结构体里的某个字段，自定义的  UnmarshalJSON MarshalJSON 这两个接口实现，所以导致反序列化不了。删除这个字段后才可以正常反序列化。

请问这个特性，该库不支持的吗？

**Comment by taowen** [comment]
不支持这两个接口。扩展是用RegisterTypeDecoder的方式实现的。

2017-04-26 14:45 GMT+08:00 emacsist <notifications@github.com>:
