### ISSUE TITLE
既然是 100% 兼容，那么首页 README 里给出的替换方案我觉得有些 low

### ISSUE THREAD

**Issue by flw-cn** [json-iterator/go#179]
不如改成直接替换 `import` 语句的方式：

替换 `import "encoding/json"` 成为 `import json "github.com/json-iterator/go"`

**Comment by flw-cn** [comment]
为什么没有改成 `import json "github.com/json-iterator/go"` 的形式呢，这个明明更常见一些呀。

**Comment by taowen** [comment]
差别不大吧

**Comment by flw-cn** [comment]
我认为差别还是蛮大的。

import 的内容一般都是统一管理的，实际项目中如果第三方依赖多的话，import 的列表就会很长。
单独加一行 `var json =` 的赋值语句，会让 import 和赋值语句相隔比较远，而这两句实际上是一气呵成的。

**Comment by Kisesy** [comment]
@flw-cn 因为默认的 jsoniter 是不完全兼容 json 的
var json = jsoniter.ConfigCompatibleWithStandardLibrary 这样才是真兼容
直接替换会有问题的

**Comment by flw-cn** [comment]
明白，你这个解释靠谱，也进一步明确了【兼容】的内涵到底是什么。

愿文档的写法容易给人造成这样的误解，以为 jsoniter 和 json 是 100% 兼容的。
