### ISSUE TITLE
Inconsistent error message for unmarshalling

### ISSUE THREAD

**Issue by sudo-suhas** [json-iterator/go#183]
Here's some code which demonstrates the inconsistency for error message between `encoding/json` and `jsoniter`:

```go
package main

import (
	"encoding/json"
	"fmt"

	jsoniter "github.com/json-iterator/go"
)

type myStruct struct {
	MyField string `json:"myField"`
}

func main() {
	bytes := []byte(`{ "myField": 0 }`)

	var v myStruct
	err := json.Unmarshal(bytes, &v)
	fmt.Printf("Error from encoding/json: \n\t%+v \n", err)

	err = jsoniter.Unmarshal(bytes, &v)
	fmt.Printf("Error from jsoniter.Unmarshal: \n\t%+v \n", err)

	err = jsoniter.ConfigFastest.Unmarshal(bytes, &v)
	fmt.Printf("Error from jsoniter.ConfigFastest.Unmarshal: \n\t%+v \n", err)
}

```

**Output:**
```
Error from encoding/json: 
	json: cannot unmarshal number into Go struct field myStruct.myField of type string 
Error from jsoniter.Unmarshal: 
	main.myStruct: MyField: ReadString: expects " or n, parsing 14 ...yField": 0... at { "myField": 0 } 
Error from jsoniter.ConfigFastest.Unmarshal: 
	main.myStruct: MyField: ReadString: expects " or n, parsing 14 ...yField": 0... at { "myField": 0 }
```

It would be ideal if I could get the error message same as `encoding/json` but I am fine with slight difference in the error message. However, the error from `jsoniter` includes the entire JSON string. In my case this string was quite large and I had difficulty in understanding the source of the problem.

**Comment by taowen** [comment]
so the problem to fix is `this string was quite large and I had difficulty in understanding the source of the problem`? How about only output the buffer around the error position?

**Comment by sudo-suhas** [comment]
Yes, that should do it. Thanks!

**Comment by sudo-suhas** [comment]
One more thing. The wording for the error is a little cryptic right now. If you could change it to something similar to the one from `encoding/json` that would be great.
