### ISSUE TITLE
is here any function to check the data is an valid JSON-encoded data

### ISSUE THREAD

**Issue by yumaojun03** [json-iterator/go#185]
is the data isn't an validate JSON data, json-iterator return nil, like this
```
	val := []byte(`{"ID":1,"Name":Reds","Colors":["Crimson","Red","Ruby","Maroon"]}`)
	fmt.Printf(jsoniter.Get(val, "Colors", 0).ToString())
```
so, when i parse json data, first step check the data format, in my program i use Valid function in "encoding/json", like this
```
	val := []byte(`{"ID":1,"Name":Reds","Colors":["Crimson","Red","Ruby","Maroon"]}`)
	if ok := json.Valid(val); !ok {
		fmt.Println("not valid JSON-encoded data")
	} else {
		fmt.Printf(jsoniter.Get(val, "Colors", 0).ToString())
	}
```

so, can you provide an data check function like standard lib's Valid?

**Comment by taowen** [comment]
jsoniter.Valid is available now

**Comment by yumaojun03** [comment]
thanks，you're so efficient
