### ISSUE TITLE
大JSON性能压测数据

### ISSUE THREAD

**Issue by zplzpl** [json-iterator/go#186]
使用了50KB的JSON数据进行压测：
goos: windows
goarch: amd64
pkg: decoder
BenchmarkJson-4                     2000            805142 ns/op
BenchmarkJson-4                     2000            804891 ns/op
BenchmarkJson-4                     2000            797622 ns/op
BenchmarkJson-4                     2000            790854 ns/op
BenchmarkJson-4                     2000            798623 ns/op
BenchmarkJsonIterator-4             2000            617892 ns/op
BenchmarkJsonIterator-4             2000            616901 ns/op
BenchmarkJsonIterator-4             2000            620901 ns/op
BenchmarkJsonIterator-4             2000            621670 ns/op
BenchmarkJsonIterator-4             2000            618648 ns/op
BenchmarkGjson-4                     500           2555799 ns/op
BenchmarkGjson-4                     500           2650347 ns/op
BenchmarkGjson-4                     500           2721288 ns/op
BenchmarkGjson-4                     500           2744298 ns/op
BenchmarkGjson-4                     500           2705194 ns/op
BenchmarkEasyjson-4                 5000            361166 ns/op
BenchmarkEasyjson-4                 5000            350532 ns/op
BenchmarkEasyjson-4                 3000            353440 ns/op
BenchmarkEasyjson-4                 5000            351234 ns/op
BenchmarkEasyjson-4                 5000            351039 ns/op
BenchmarkFFjson-4                   5000            350137 ns/op
BenchmarkFFjson-4                   5000            359054 ns/op
BenchmarkFFjson-4                   5000            351936 ns/op
BenchmarkFFjson-4                   5000            353345 ns/op
BenchmarkFFjson-4                   5000            353145 ns/op
PASS
ok      decoder 40.412s

CPU：intel i5-7300U CPU @ 2.60GHz 2.71GHz

性能上出现了这样的差异，是有什么因素可能造成这样？

**Comment by zplzpl** [comment]
压测环境存在问题；下面的数据是再重新压测过的：
BenchmarkJson-4                     3000           1774066 ns/op          107688 B/op       1785 allocs/op
BenchmarkJsonIterator-4            10000            997047 ns/op          210208 B/op       2592 allocs/op
BenchmarkGjson-4                    5000           1500791 ns/op          148064 B/op        662 allocs/op
BenchmarkEasyjson-4                10000            866409 ns/op           99008 B/op       1167 allocs/op

**Comment by zplzpl** [comment]
goos: windows
goarch: amd64
pkg: decoder
BenchmarkJson-4                    20000            792158 ns/op          107688 B/op       1785 allocs/op
BenchmarkJson-4                    20000            811209 ns/op          107688 B/op       1785 allocs/op
BenchmarkJson-4                    20000            822070 ns/op          107688 B/op       1785 allocs/op
BenchmarkJson-4                    20000            819483 ns/op          107688 B/op       1785 allocs/op
BenchmarkJson-4                    20000            824242 ns/op          107688 B/op       1785 allocs/op
BenchmarkJsonIterator-4            30000            454442 ns/op          210208 B/op       2592 allocs/op
BenchmarkJsonIterator-4            30000            458327 ns/op          210208 B/op       2592 allocs/op
BenchmarkJsonIterator-4            30000            456524 ns/op          210208 B/op       2592 allocs/op
BenchmarkJsonIterator-4            30000            458320 ns/op          210208 B/op       2592 allocs/op
BenchmarkJsonIterator-4            30000            449294 ns/op          210208 B/op       2592 allocs/op
BenchmarkGjson-4                   30000            566117 ns/op          148064 B/op        662 allocs/op
BenchmarkGjson-4                   30000            571665 ns/op          148064 B/op        662 allocs/op
BenchmarkGjson-4                   30000            567482 ns/op          148064 B/op        662 allocs/op
BenchmarkGjson-4                   30000            567610 ns/op          148064 B/op        662 allocs/op
BenchmarkGjson-4                   30000            568647 ns/op          148064 B/op        662 allocs/op
BenchmarkEasyjson-4                50000            314751 ns/op           99008 B/op       1167 allocs/op
BenchmarkEasyjson-4                50000            314844 ns/op           99008 B/op       1167 allocs/op
BenchmarkEasyjson-4                50000            314359 ns/op           99008 B/op       1167 allocs/op
BenchmarkEasyjson-4                50000            313514 ns/op           99008 B/op       1167 allocs/op
BenchmarkEasyjson-4                50000            314902 ns/op           99008 B/op       1167 allocs/op
BenchmarkFFjson-4                  20000            821535 ns/op          107688 B/op       1785 allocs/op
BenchmarkFFjson-4                  20000            824450 ns/op          107688 B/op       1785 allocs/op
BenchmarkFFjson-4                  20000            824703 ns/op          107688 B/op       1785 allocs/op
BenchmarkFFjson-4                  20000            846503 ns/op          107688 B/op       1785 allocs/op
BenchmarkFFjson-4                  20000            820634 ns/op          107688 B/op       1785 allocs/op
PASS
ok      decoder 546.697s

**Comment by zplzpl** [comment]
goos: windows
goarch: amd64
pkg: decoder
BenchmarkJson-4                    20000            792158 ns/op          107688 B/op       1785 allocs/op
BenchmarkJson-4                    20000            811209 ns/op          107688 B/op       1785 allocs/op
BenchmarkJson-4                    20000            822070 ns/op          107688 B/op       1785 allocs/op
BenchmarkJson-4                    20000            819483 ns/op          107688 B/op       1785 allocs/op
BenchmarkJson-4                    20000            824242 ns/op          107688 B/op       1785 allocs/op
BenchmarkJsonIterator-4            30000            454442 ns/op          210208 B/op       2592 allocs/op
BenchmarkJsonIterator-4            30000            458327 ns/op          210208 B/op       2592 allocs/op
BenchmarkJsonIterator-4            30000            456524 ns/op          210208 B/op       2592 allocs/op
BenchmarkJsonIterator-4            30000            458320 ns/op          210208 B/op       2592 allocs/op
BenchmarkJsonIterator-4            30000            449294 ns/op          210208 B/op       2592 allocs/op
BenchmarkGjson-4                   30000            566117 ns/op          148064 B/op        662 allocs/op
BenchmarkGjson-4                   30000            571665 ns/op          148064 B/op        662 allocs/op
BenchmarkGjson-4                   30000            567482 ns/op          148064 B/op        662 allocs/op
BenchmarkGjson-4                   30000            567610 ns/op          148064 B/op        662 allocs/op
BenchmarkGjson-4                   30000            568647 ns/op          148064 B/op        662 allocs/op
BenchmarkEasyjson-4                50000            314751 ns/op           99008 B/op       1167 allocs/op
BenchmarkEasyjson-4                50000            314844 ns/op           99008 B/op       1167 allocs/op
BenchmarkEasyjson-4                50000            314359 ns/op           99008 B/op       1167 allocs/op
BenchmarkEasyjson-4                50000            313514 ns/op           99008 B/op       1167 allocs/op
BenchmarkEasyjson-4                50000            314902 ns/op           99008 B/op       1167 allocs/op

**Comment by taowen** [comment]
show me the code
