### ISSUE TITLE
1 << 49

### ISSUE THREAD

**Issue by imkos** [json-iterator/go#196]
srcPtr := (\*[1 << 49]byte)(slice.Data)
dstPtr := (\*[1 << 49]byte)(dst)
这个已经超出32位的系统编译范围了， 为何不对此go 文件增加 build 的tag 只用于64位以上。而且 这个切片 是不是 有点大

array bound is too large
constant 562949953421312 overflows int

是否 考虑用 int(^uint(0) >> 1)

**Comment by taowen** [comment]
good idea ! 给个 pr 吧

**Comment by lempiy** [comment]
Is this fixed ?
looks like max size is still [1 << 49]

**Comment by taowen** [comment]
it should be fixed

**Comment by lempiy** [comment]
yes, I had an old version. Sorry.
