### ISSUE TITLE
jsoniter crashes with custom encoders for map

### ISSUE THREAD

**Issue by sreekanth-cb** [json-iterator/go#205]
The issue reported in #204 is still reproducible, please check the below stack. Its reproducible with the sample program attached in #204 .

go run mapFails.go 
JSON Res {"total":100,"errMaps":{"first":"First Error","second":"Second Error"}}  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x10ebbc8]

goroutine 1 [running]:
main.encodeMap(0xc420092330, 0xc420094300)
	/Users/sreekanth/jsoniter/mapFails.go:48 +0x48
github.com/json-iterator/go.(*funcEncoder).Encode(0xc42008c0f0, 0xc420092330, 0xc420094300)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_reflect_extension.go:99 +0x3d
github.com/json-iterator/go.(*optionalMapEncoder).Encode(0xc42008c360, 0xc42008c298, 0xc420094300)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_reflect.go:144 +0x4f
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc4200883e0, 0xc42008c290, 0xc420094300)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_reflect_object.go:118 +0x5c
github.com/json-iterator/go.(*structEncoder).Encode(0xc420088480, 0xc42008c290, 0xc420094300)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_reflect_object.go:155 +0xc2
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc42008c3c0, 0xc42008c3d8, 0xc420094300)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_reflect.go:124 +0x4f
github.com/json-iterator/go.WriteToStream(0x10fafe0, 0xc42008c290, 0xc420094300, 0x11c3c40, 0xc42008c3c0)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_reflect.go:47 +0xd5
github.com/json-iterator/go.(*OptionalEncoder).EncodeInterface(0xc42008c3c0, 0x10fafe0, 0xc42008c290, 0xc420094300)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_reflect.go:129 +0x55
github.com/json-iterator/go.(*Stream).WriteVal(0xc420094300, 0x10fafe0, 0xc42008c290)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_reflect.go:252 +0xe4
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc420096100, 0x10fafe0, 0xc42008c290, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_config.go:263 +0xdb
github.com/json-iterator/go.Marshal(0x10fafe0, 0xc42008c290, 0xc420041ea8, 0x1, 0x1, 0x53, 0x0)
	/Users/sreekanth/workspace_json/godeps/src/github.com/json-iterator/go/feature_adapter.go:43 +0x49
main.jsoniterMarshal(0x64, 0xc420092330)
	/Users/sreekanth/jsoniter/mapFails.go:12 +0x87
main.main()
	/Users/sreekanth/jsoniter/mapFails.go:66 +0x296
exit status 2

**Comment by taowen** [comment]
the ptr is a map, not pointer to the map. so you need to add one line in your encoder:

```go
func encodeMap(ptr unsafe.Pointer, stream *Stream) {
	mapPtr := unsafe.Pointer(&ptr) // ptr is not *ErrMap, but ErrMap itself
	iem := *((*ErrMap)(mapPtr))
	//log.Printf("\nval-> %+v", iem)
	if iem != nil {
		tmp := make(map[string]string, len(iem))
		for k, v := range iem {
			tmp[k] = v.Error()
		}
		stream.WriteVal(tmp)
	}
}
```
