### ISSUE TITLE
panic on unmarshal

### ISSUE THREAD

**Issue by LaconisIves** [json-iterator/go#206]
package main

import (
	"encoding/json"
	"github.com/json-iterator/go"
	"log"
)

type T struct {
	X int
}

type TT struct {
	T *T
}

func main() {
	data := []byte(`{"A":0}`)
	var t *T
	// return non-nil error
	if err := json.Unmarshal(data, t); err != nil {
		log.Println(err)
	}
	// return nil error
	if err := jsoniter.Unmarshal(data, t); err != nil {
		log.Println(err)
	}
	var tt *TT
	// return non-nil error
	if err := json.Unmarshal(data, tt.T); err != nil {
		log.Println(err)
	}
	// panic
	if err := jsoniter.Unmarshal(data, tt.T); err != nil {
		log.Println(err)
	}
}

**Comment by taowen** [comment]
` json.Unmarshal(data, tt.T);`

isn't tt being nil at this point?
