### ISSUE TITLE
Unquoted keys support

### ISSUE THREAD

**Issue by Irioth** [json-iterator/go#213]
There doesn't seem an option for parsing such bad json

`{ time:"1234", cod:200, url:"/users" }`

Could it be supported?

**Comment by taowen** [comment]
this is not valid json. it will not be supported.

**Comment by mgood** [comment]
That's valid in JavaScript, but not JSON. I've used the JavaScript parser from https://github.com/robertkrimen/otto to decode similar structures into an AST, and then converted that to Go data structures.
