### ISSUE TITLE
float64 marshal silently lose data 

### ISSUE THREAD

**Issue by sreekanth-cb** [json-iterator/go#22]
float64 marshal loses data.
please see the sample :
`
import (
	"log"
	"encoding/json"
	jsoniter "github.com/json-iterator/go"
)

type example struct {
	Val float64 `json:"val"`
}

func main() {
	v := example{0.000000099}
	bytes, err := jsoniter.Marshal(v)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("jsoniter got: %s", string(bytes))
	bytes, err = json.Marshal(v)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("json got: %s", string(bytes))
}

`

**Comment by taowen** [comment]
fixed, use `EnableLossyFloatMarshalling()` to restore the current behavior
