### ISSUE TITLE
大量请求时,内存泄漏问题

### ISSUE THREAD

**Issue by ahlzhang** [json-iterator/go#220]
目前我有一个项目，每天晚上需要更新大量的数据约300W条数据。通过更新发现内存会越来越大。

我写了个testing.更新100000条数据。最后内存的结果为：
![image](https://user-images.githubusercontent.com/16819060/34639877-57c12d82-f323-11e7-93e1-a651e4360742.png)

随着更新的数据越来越多，`github.com/json-iterator/go.(*Iterator).readStringSlowPath` 占用的内存会越来越大。

请帮忙看一下是什么原因？谢谢

**Comment by taowen** [comment]
可能是因为复用了iterator https://github.com/json-iterator/go/blob/master/feature_config.go#L290

具体的问题还是要给测试数据以及复现的方式。你看的是内存分配数量，还是内存占用数量？如果是分配内存多，应该是正常的吧。如果是占用的内存不释放，那要看是什么对象hold住了内存。

**Comment by ahlzhang** [comment]
我按你的方案，直接构造了一个Iterator对象，再次testing了一次。
`func (cfg *frozenConfig) BorrowIterator(data []byte) *Iterator {
	//select {
	//case iter := <-cfg.iteratorPool:
	//	iter.ResetBytes(data)
	//	return iter
	//default:
	return ParseBytes(cfg, data)
	//}
}`

跑出来的结果相差不多。

![image](https://user-images.githubusercontent.com/16819060/34648006-57afd1d2-f3cc-11e7-87c1-84f317ffeeed.png)

**Comment by taowen** [comment]
你的问题是运行过程中持续inuse的内存一直增大。需要用 -inuse_space 来看

参见 https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/

**Comment by ahlzhang** [comment]
用标准库比你这个还要大一点。我现在不是很清楚到底是哪里出了问题，我用pprof查出来我程序的占用情况300多M,但进程里的占用率是600多M。而且一直不回收。
![image](https://user-images.githubusercontent.com/16819060/34657234-3936239e-f45f-11e7-93b5-7096baf524bd.png)
![image](https://user-images.githubusercontent.com/16819060/34657238-41a6cb5a-f45f-11e7-946e-3020680525df.png)

**Comment by taowen** [comment]
那应该是你的业务代码的问题。如果标准库也有问题，那应该不大可能是json库可以解决的。

**Comment by ahlzhang** [comment]
问题已经解决，是我没有搞清楚GO的GC机制。。

**Comment by huhuyou2** [comment]
@ahlzhang 是否可以抽空出个问题解决的分享，我也遇到类似的问题，不知道怎么处理，非常感谢

**Comment by ahlzhang** [comment]
@huhuyou2 把你的情况发出来，我当时的情况是每个json的量很大，我切分了json解决的这个问题。你把你的情况发出来，看下是不是与我相同的问题。

**Comment by neicunlideyu** [comment]
> @huhuyou2 把你的情况发出来，我当时的情况是每个json的量很大，我切分了json解决的这个问题。你把你的情况发出来，看下是不是与我相同的问题。

我也遇到了同样的问题，怀疑内存泄漏。请问切分json可以解决内存泄漏的问题？

**Comment by ahlzhang** [comment]
切分就解决了。
