### ISSUE TITLE
using jsoniters NewDecoder(os.Stdin) errors out on time.Time

### ISSUE THREAD

**Issue by akacase** [json-iterator/go#221]
json record (scrubbed): `{"id":"","ip":"192.168.2.1","mac":"AMAC","data":{"NAME":"a-host","SPEED":"40 Gbps","DUPLEX":"full","HOSTNAME":"a-host","MAC_ADDRESS":"AMAC","STATE":"up","TYPE":"10","DESCRIPTION":"a-host","IP_ADDRESS":"192.168.2.1","LAST_SEEN":"2018-01-06 02:02:35"},"found":"2018-01-06T02:02:35Z"}`

and when trying to Decode from `os.Stdin` I receive this error message:
```
readObjectStart: expect { or n, but found , error found in #10 byte of ...|2:02:35Z"}
|..., bigger context ...|und":"2018-01-06T02:02:35Z"}
|...
```
The API is setup via `json = jsoniter.ConfigFastest` -- I've also tried all other configs with the same error. The output was generated via jsoniters encoder as well with the same config, `jsoniter.ConfigFastest`

Here's the struct it's trying to marshal into:
```
Source struct {                                                                                                                                                              
                ID       string      `json:"id" bson:"_id,omitempty"`                                                                                                                
                Source   string      `json:"source,omitempty" bson:"source,omitempty"`                                                                                               
                Hostname string      `json:"hostname,omitempty" bson:"hostname,omitempty"`                                                                                           
                IP       string      `json:"ip,omitempty" bson:"-"`                                                                                                                  
                Mac      string      `json:"mac,omitempty" bson:"-"`                                                                                                                 
                Network  string      `json:"network,omitempty" bson:"network,omitempty"`                                                                                             
                Data     interface{} `json:"data,omitempty" bson:"data,omitempty"`                                                                                                   
                Found    time.Time   `json:"found" bson:"found,omitempty"`                                                                                                           
                RunID    string      `json:"runid,omitempty" bson:"runid,omitempty"`                                                                                                 
        } 
```

**Comment by taowen** [comment]
two things

1. first verify the stdin input is utf8
2. try encoding/json to see if that works

**Comment by akacase** [comment]
input is valid utf8 -- I can take input and ` iconv -f UTF-8 test.json > test2.json` and feed that file into my test program and the decoder still errors out with the same error from above. I seem to be missing the point of no. 2, it's already valid json going out of the encoder on the other side. Thank!

**Comment by taowen** [comment]
if "encoding/json" is also giving out error, you may check your input again.

**Comment by akacase** [comment]
`"encoding/json"` is not erroring out on this example as once thought, the timestamp in the code was just being reset. it still errors out while using `json-iterator` we can close this issue if you'd like.
