### ISSUE TITLE
Config for marshalling json using different cases?

### ISSUE THREAD

**Issue by pyros2097** [json-iterator/go#226]
I would like to have a default config that would marshal my golang structs to json which has all keys camelCased or any other case. Is this possible? This way I don't need to add struct tag literals for all my fields with the camelCase of the fieldName.

**Comment by taowen** [comment]
https://github.com/json-iterator/go/blob/8fbed91768da7ec837f4e2c793d0d5538d307646/extra/naming_strategy.go

**Comment by pyros2097** [comment]
Thank You. :smile:
