### ISSUE TITLE
Support DisallowUnknownFields in golang 1.10

### ISSUE THREAD

**Issue by rickypai** [json-iterator/go#230]
Hi,

Thanks a lot for creating this package. It has been very helpful in my project. One small request:
json package in golang 1.10 will introduce `DisallowUnknownFields()` which would throw an error if a field is missing during unmarshaling. it would be great if json-iterator can support the same configuration.

Reference change in golang:
https://go-review.googlesource.com/c/go/+/74830

Thank you for considering this request!

**Comment by taowen** [comment]
it is supported now
