### ISSUE TITLE
jsoniter.Unmarshal解析json.RawMessage数据出现异常

### ISSUE THREAD

**Issue by WenhaiLin** [json-iterator/go#232]
```
type connectServer struct {
	UT    int64
	UID   int32
	Token string
	DID   int16
}
```

数据：
`"{\"UID\":10046,\"UT\":1517378737,\"DID\":20855,\"Token\":\"fe3e67b774fa4a5cbcbbf1238d523851\"}"`

错误：
` err:readObjectStart: expect { or n, but found ", error found in #1 byte of ...|"{\"UID\":1|..., bigger context ...|"{\"UID\":10046,\"UT\":1517378737,\"DID\":20855,\"T|...`

**Comment by WenhaiLin** [comment]
我这边使用错误

**Comment by fananchong** [comment]
> 我这边使用错误

你怎么使用错误，会提示这个。我也出现一次这个错误，但是还没找到原因
