### ISSUE TITLE
能不能支持map key的自定义

### ISSUE THREAD

**Issue by sankeyou** [json-iterator/go#235]
现在只支持value的根据类型的自定义函数 不支持key的?

**Comment by taowen** [comment]
```go
type TextMarshaler interface {
	MarshalText() (text []byte, err error)
}
```

implement this interface for your type of map key.

**Comment by sankeyou** [comment]
json-iterator\go\output_tests\map_key_text_marshal\string_alias该示例并没有效果
keyType的MarshalText()与UnmarshalText()都没有执行？
