### ISSUE TITLE
maybe compatible with go1.10?

### ISSUE THREAD

**Issue by deafwolf** [json-iterator/go#240]
go 1.10 was released with strings.Builder, maybe jsoniter could use it for more faster and avoid panic.

**Comment by taowen** [comment]
* faster: may be we can avoid one allocation here: https://github.com/json-iterator/go/blob/master/iter_str.go#L41 
* avoid panic: how?

**Comment by deafwolf** [comment]
faster: yes, but not enough. what about refact the Stream? there is a []byte in it
avoid panic: I had saw someone report panic #233 without test code, maybe it was cause by using unsafe, so I think official Builder is a little safer.

**Comment by taowen** [comment]
unsafe will not cause panic. incorrect use of unsafe will. The new implementation has incorporated reflect2 package, which copies the underlying code from golang reflect implementation. A couple of incorrect usage of unsafe has been eliminated.

For marshaling into stream, the `[]byte` is necessary. We can not cast string to `[]byte` and write to writer. For two reasons: the string might contain character need escape, which means the `[]byte` will be different. Second, flushing to writer should be buffered, the syscall itself is also expensive.

**Comment by deafwolf** [comment]
ok, got it.
