### ISSUE TITLE
MarshalText()不起效果

### ISSUE THREAD

**Issue by sankeyou** [json-iterator/go#242]
json-iterator\go\output_tests\map_key_text_marshal\string_alias该示例并没有效果
keyType的MarshalText()与UnmarshalText()都没有执行？

**Comment by sankeyou** [comment]
结果到是一样的
我试了最新版
`https://github.com/json-iterator/go/blob/master/type_tests/map_key_test.go`
这个struct的有效 stirngkey的也是无效的，你既然这样写了，难道测试了也可以？我这go1.93和1.10都不行

**Comment by taowen** [comment]
我测的是和标准库的兼容性。不生效，就是两个实现都不生效。生效就是两个实现都生效。

```go
func ExampleMapKey() {
	hello := MyKey("hello")
	output, _ := Marshal(map[*MyKey]string{&hello: "world"})
	fmt.Println(string(output))
	obj := map[*MyKey]string{}
	Unmarshal(output, &obj)
	for k, v := range obj {
		fmt.Println(*k, v)
	}
	// Output:
	// {"Hello":"world"}
	// Hel world
}

type MyKey string


func (m *MyKey) MarshalText() ([]byte, error) {
	return []byte(strings.Replace(string(*m), "h", "H", -1)), nil
}

func (m *MyKey) UnmarshalText(text []byte) error {
	*m = MyKey(text[:3])
	return nil
}
```

看来只有设置成指针才能生效。标准库也是这样的行为。

**Comment by sankeyou** [comment]
那我想修改map的key就没有好办法了吧，否则怎么实现小驼峰比较好呢？

**Comment by taowen** [comment]
扩展了一下extension，你可以自定义map key的编解码方式了：https://github.com/json-iterator/go/blob/master/extension_tests/extension_test.go#L51
