### ISSUE TITLE
希望能够补充README的说明

### ISSUE THREAD

**Issue by vearne** [json-iterator/go#256]
根据测试，对Map进行encode，json-iterator和标准库性能提升不大，希望在README中，能够做出说明，以免误导用户
测试结果说明
http://vearne.cc/archives/433

耗时
|json库|map|struct|
|:---|:---|:---|
|json-iterator|12,612,965 ns|1,763,779 ns|
|encoding/json|12,807,660 ns|2,652,197 ns|

**Comment by taowen** [comment]
marshal string 基本上就是在做memory copy，没有提升也是在预期之中。

**Comment by vearne** [comment]
能否在README里面说明一下。
