### ISSUE TITLE
jsoniter BorrowStream and concurrency

### ISSUE THREAD

**Issue by sudo-suhas** [json-iterator/go#258]
From the recommendations for performance in http://jsoniter.com/migrate-from-go-std.html

> reuse the underlying Stream or Iterator instance. `jsoniter.ConfigFastest.BorrowIterator` or `jsoniter.ConfigFastest.BorrowStream`. Just remember to return them when done.

Based on this and example tests([json-iterator/go:example_test.go@`f89479f`#L48-L68](https://github.com/json-iterator/go/blob/f89479f5c0d83b365504d632ab57390447bb406a/example_test.go#L48-L68)), I have the following helper function:

```go
var jcf = jsoniter.ConfigCompatibleWithStandardLibrary

func marshal(v interface{}) ([]byte, error) {
	stream := jcf.BorrowStream(nil)
	defer jcf.ReturnStream(stream)

	stream.WriteVal(v)

	if stream.Error != nil {
		return nil, stream.Error
	}

	return stream.Buffer(), nil
}
```

However, I observed that the marshalled value was malformed in some cases with high concurrency. Here's a repo which demonstrates this issue - https://github.com/sudo-suhas/jsoniter-parallel.

Should I be protecting `jsoniter.ConfigFastest.BorrowStream` with a mutex?

**Comment by taowen** [comment]
stream.Buffer() is only valid when you hold the stream. If you returned the stream, you need to copy the `[]byte`

**Comment by sudo-suhas** [comment]
I see, thanks @taowen. If I were to copy the `[]byte`, that would be equivalent to the current `Marshal` implementation in `jsoniter` right?

**Comment by taowen** [comment]
yes
