### ISSUE TITLE
Error json syntax when marshaling nil RawMessage

### ISSUE THREAD

**Issue by wanglovesyang** [json-iterator/go#259]
when an instance was defined as follows

import json "github.com/json-iterator/go"

b := &struct {
    ID int `json:"id"`
    Etc json.RawMessage `json:"etc"`
}{
  ID:0,
  Etc:nil,
}

fm.Println(json,MarshalAsString(b))

the output seems to be like

{
  "id":0,
  "etc":
}

Obviously, this bug leads to a incorrect syntax of json.

**Comment by taowen** [comment]
use `jsoniter.ConfigCompatibleWithStandardLibrary.Marshal`
