### ISSUE TITLE
Private fields bugs when renaming

### ISSUE THREAD

**Issue by gobigshark** [json-iterator/go#260]
## **Failed to support private fields when renaming.**
`package main

import (
	"fmt"

	jsoniter "github.com/json-iterator/go"
	"github.com/json-iterator/go/extra"
)

func main() {
	extra.SupportPrivateFields()
	type TestObject struct {
		field string `json:"myfield"`
	}
	obj := TestObject{}
	jsoniter.UnmarshalFromString(`{"myfield":"Hello"}`, &obj)
	fmt.Println(obj.field) // Output empty string instead of "Hello"
}`

**Comment by ceshihao** [comment]
It is because your field `field` is unexported. It is introduced by #175 

@taowen said
> if field is unexported, the field names will be empty slice. field names are used to decode or encode one go field from multiple json field. if is empty, meaning it is not present in json.

I am wondering whether unexported field need to be support if using the private field extension?
