### ISSUE TITLE
ToVal(map[string]string)   func doesn't work fine where json string contains Array

### ISSUE THREAD

**Issue by dozysun** [json-iterator/go#262]
I have a json string and want use ToVal{} func covert it to map[string]string,   if json string contains nil ,int will parse it to "" and convert correctly, that's what i want, but if string  contains  Array or map , it will stop convert at the array or map param and wouldn't convert the whole string.  
![image](https://user-images.githubusercontent.com/8655323/38667839-20e3ea32-3e75-11e8-87eb-1a9934c69114.png)
will you fix it, or i have to use map[string]interface{} to convert the string 

eg: fist map use map[string]string, second is map[string]interface{}

**Comment by taowen** [comment]
please use `map[string]interface{}`
