### ISSUE TITLE
Unmarshal fails for if the struct contains an interface type

### ISSUE THREAD

**Issue by uttee** [json-iterator/go#269]
I am trying to marshal and unmarshal the struct with interface type. I can marshal it, but unmarshal fails.

Here is the go code
package main
import (
	"github.com/json-iterator/go"
	"fmt"
)

type ValInterface interface {
	isvalidval()
}

type mystruct struct {
	Kind ValInterface
}

type stringVal struct {
	StringVal string
}

func (*stringVal) isvalidval(){}

func main() {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var resultMy mystruct

	my := mystruct{}
	my.Kind = &stringVal{StringVal:"asdasd"}

	str,err := json.Marshal(&my)
	if err != nil {
		fmt.Errorf("Marshalling failed")
		return
	}
	fmt.Printf("\n%s\n", str)
	fmt.Printf("\n----------------\n")
	err = json.Unmarshal(str, &resultMy)
	if err != nil {
		fmt.Printf("UNMarshalling failed %v\n", err)
		return
	}
}

Output:
{"Kind":{"StringVal":"asdasd"}}

----------------
UNMarshalling failed main.mystruct.Kind: decode non empty interface: can not unmarshal into nil, error found in #8 byte of ...|{"Kind":{"StringVa|..., bigger context ...|{"Kind":{"StringVal":"asdasd"}}|...

Process finished with exit code 0

**Comment by uttee** [comment]
I don't think unmarshalling a json to a struct that contains interface type is possible. There is no way for unmarshaller to figure out what concrete type to unmarshal it to. I added this issue to confirm this assumption, since I new to go.

**Comment by taowen** [comment]
there is no standard representation of type information in the json, so unmarshalling back as a interface is non-standard. You can customize the behavior using extension.

**Comment by uttee** [comment]
Thanks Taowen!
