### ISSUE TITLE
Memory consumption on large JSON files

### ISSUE THREAD

**Issue by BorisKozo** [json-iterator/go#270]
Hi,
We are using your excellent project for an application which is heavily consuming memory so we are trying to reduce every bit we can. In our use case we have large JSON files and we extract a particular value from it without extracting the entire JSON. This is achieved by extracting only one level each time, taking the relevant node from that level and then doing it again until we reach our node. The rest of the JSON remains encoded as a byte array in jsoniter.RawMessage.

The problem is that for each level we unmarshal it copies all the rest of the file into a different array thus doubling the memory usage.

To overcome this I commented out the lines here: https://github.com/json-iterator/go/blob/master/iter_skip.go#L62

and replaced them with ````return remaining````

This creates a pointer to the original array instead of copying.
**Is this solution correct in terms of functionality?** We never modify any of the arrays anyway (does anyone ever do that?) so copying them all the time seems like a waste of memory.

If this is correct, would it be possible to create a PR with this change (could be under a configuration flag for backward compatibility) and are there other areas that need to be modified?

Thanks,
Boris

**Comment by taowen** [comment]
this is incorrect, as remaining is a slice on top of the read buffer. the buffer will be reused, so the remaining content will be changed.

you should read and consume the input in a streaming way to reduce memory consumption.

**Comment by BorisKozo** [comment]
Good thing I asked then 😃 
Is there an example or documentation somewhere how to use the streaming way?

**Comment by taowen** [comment]
checkout https://github.com/json-iterator/go/blob/master/misc_tests/jsoniter_iterator_test.go
