### ISSUE TITLE
[]byte marshaled to null

### ISSUE THREAD

**Issue by ash2k** [json-iterator/go#272]
One of the fuzz tests in Kubernetes caught an issue:
This library:
```json
{"metadata":{"selfLink":"Ǭ`/F苫ŽȢ噯榋C","resourceVersion":"4597642297830476577"},"items":[{"metadata":{"name":"玿j情1 蔝","generateName":"萀枦đ ","uid":".愥+ǽķ蓧u岏V","resourceVersion":"13323996552230461162","creationTimestamp":null},"data":{"輣 兀zʩL:Ģ梸ïĭ":"MŞFƤ趻Ă癆萃猷S幸4"},"binaryData":{"Ȟ櫤薯WǱĥȂ":null}}]}
```
`encoding/json`:
```json
{"metadata":{"selfLink":"Ǭ`/F苫ŽȢ噯榋C","resourceVersion":"4597642297830476577"},"items":[{"metadata":{"name":"玿j情1 蔝","generateName":"萀枦đ ","uid":".愥+ǽķ蓧u岏V","resourceVersion":"13323996552230461162","creationTimestamp":null},"data":{"輣 兀zʩL:Ģ梸ïĭ":"MŞFƤ趻Ă癆萃猷S幸4"},"binaryData":{"Ȟ櫤薯WǱĥȂ":""}}]}
```

Notice how at the very end of the json the value in the map is not the same.
BinaryData field is declared like this:
```go
BinaryData map[string][]byte `json:"binaryData,omitempty"`
```
https://github.com/kubernetes/kubernetes/blob/8f20a815e5ef27d4d247e42bff90e42706397ca2/staging/src/k8s.io/api/core/v1/types.go#L4742

Trying to migrate all `encoding/json` uses to this library in this PR https://github.com/kubernetes/kubernetes/pull/63284

This is using commit 2ddf6d758266fcb080a4f9e054b9f292c85e6798

**Comment by panjunjie** [comment]
我也碰到这种情况了：
jsonStr:={"file":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAMAAAAoyzS7AAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAAGUExURf///wAAAFXC034AAAABdFJOUwBA5thmAAAADElEQVR42mJgAAgwAAACAAFPbVnhAAAAAElFTkSuQmCC"}
json 字符串，其中 file 属性 是 []byte 对象，使用 json-iterator 转换成对象，file 是空值：
json.Unmarshal([]byte(jsonStr), &fileStruct)

目前只能切换回自带的 "encoding/json"

**Comment by thockin** [comment]
https://play.golang.org/p/nx9cyeks1ne

shows that stdlib json encodes a nil slice as "null" but decodes `""` and `"null"` as a non-nil empty slice

https://play.golang.org/p/lOSZs9_fzAB

corroborates that []int follows the same pattern

@ash2k - in my experience, if you write the testcase for json-iterator that shows this behavioral difference, they will fix it :)  The test case should be trivial.  https://github.com/json-iterator/go/blob/master/type_tests/map_test.go  I am not sure why it doesn't get caught already, truthfully.

**Comment by taowen** [comment]
sorry for the delay, the base64 decode issue has been fixed

**Comment by stevenjohnstone** [comment]
I'm not sure this has been fixed:

```
package main

import (
        "encoding/json"
        "fmt"

        jsoniter "github.com/json-iterator/go"
)

var json2 = jsoniter.ConfigCompatibleWithStandardLibrary

func main() {

        m := map[string][]byte{
                "foo": []byte{},
        }

        data2, err := json2.Marshal(m)
        if err != nil {
                panic(err)
        }
        fmt.Printf("jsoniter output       %s (%v)\n", string(data2), data2)

        data, err := json.Marshal(m)
        if err != nil {
                panic(err)
        }
        fmt.Printf("encoding/json output   %s (%v)\n", string(data), data)

}
```

```
$ go run main.go 
jsoniter output       {"foo":null} ([123 34 102 111 111 34 58 110 117 108 108 125])
encoding/json output   {"foo":""} ([123 34 102 111 111 34 58 34 34 125])
```

**Comment by maiamcc** [comment]
I'm also seeing `[]byte{}` being marshaled to `null` rather than `""`. Any chance of this getting addressed?

**Comment by nikhita** [comment]
Fixed in https://github.com/json-iterator/go/pull/371
