### ISSUE TITLE
json:omitempty doesn't work with set naming convetion

### ISSUE THREAD

**Issue by shdunning** [json-iterator/go#277]
One of the cool features of this library is that we can set field naming strategy like so...

`extra.SetNamingStrategy(extra.LowerCaseWithUnderscores)`

...however `json:"omitempty"` does not work as expected with naming convention. For example:

```
type Foo struct {
	Bar string `json:"omitempty"`
}
```

In the example above we would expect the field `bar` to be present in our Marshaled response if the object being Marshaled contains a value for `Foo.Bar`. Actual behavior is that it will always be omitted until we change the struct definition to contain the name of the field to marshal into, which defeats the purpose of using a set naming strategy. For example, this works:

```
type Foo struct {
	Bar string `json:"omitempty,bar"`
}
```

**Comment by taowen** [comment]
should use `json:",omitempty"`
