### ISSUE TITLE
Jsoniter is not 100% compatible with json, encoutering issue with float conversion

### ISSUE THREAD

**Issue by tungnk1993** [json-iterator/go#283]
[https://play.golang.org/p/9Kc_tdIXN6o](https://play.golang.org/p/9Kc_tdIXN6o)

The code fails for jsoniter, but passed for default json
If we uncomment the [][2]float64 in the struct, both code will pass

**Comment by taowen** [comment]
can not reproduce the bug you reported by test

https://github.com/json-iterator/go/commit/720ab8dc7f30224c924d13f0865950bc6fd7dcea
