### ISSUE TITLE
wishlist: do not depend on modern-go/*

### ISSUE THREAD

**Issue by TheTincho** [json-iterator/go#284]
Hi,

I have just prepared and uploaded version 1.0.6 of json-iterator to Debian, as that is the last version without the modern-go dependencies, which are not yet present in Debian.

In parallel, I was packaging these dependencies, so I can upload 1.1.3 soon. Sadly, I discovered some problems with that collection of libraries: circular dependencies between different repos (reflect2 -> test -> reflect2), using a private (possibly patched) version of stretchr/testify, and a long tail of dependencies that never seems to end..

So, I wanted to request, if it is feasible, to avoid depending on these libraries. I presume they are not critical, as they were not needed until 1.06.

Thanks.

**Comment by taowen** [comment]
reflect2 does not depend on test. Which tool reports circular dependency?

**Comment by TheTincho** [comment]
On 11/06/18 03:56, Tao Wen wrote:
> reflect2 does not depend on test. Which tool reports circular dependency?

The reflect2 tests depend on test, so to build the reflect2 package
(which includes running the tests), I need the test package.

-- 
Martín Ferrari (Tincho)

**Comment by taowen** [comment]
reflect2 no longer depends on tests now

**Comment by TheTincho** [comment]
There was no need to (re)move the tests, I was already ignoring them to avoid this problem.

But the issues with using a private copy of testify, and the long chain of dependencies (including gls, which ships arch-specific code that means it won't work in many Debian architectures) are still there.
