### ISSUE TITLE
jsoniter should ignore whitespace after JSON expression

### ISSUE THREAD

**Issue by hknutzen** [json-iterator/go#288]
https://play.golang.org/p/j1tgpWn9CgE

RFC 4627 states: Insignificant whitespace is allowed before or after any of the six structural characters.
But jsoniter fails with:
`UnmarshalFromString: there are bytes left after unmarshal, parsing 2 ...{}... at {} `

**Comment by taowen** [comment]
which version are you using? I can not reproduce your bug

```go
func Test_trailing_garbage(t *testing.T) {
	should := require.New(t)
	var i struct{}
	err := jsoniter.UnmarshalFromString("{} ", &i)
	should.Nil(err)
}
```

**Comment by hknutzen** [comment]
Sorry, I accidentally used an old version from 2017.
I thought it was freshly installed with `go get github.com/json-iterator/go`, but didn't recognize that an old version already was on my system.
After an `go get -u ...` the bug disappeared for me too.
