### ISSUE TITLE
Field (like ID) change to i_d after extra.SetNamingStrategy(LowerCaseWithUnderscores) enable , Is there any way to fixe or enhance

### ISSUE THREAD

**Issue by junkao** [json-iterator/go#294]
Field (like ID) change to i_d after extra.SetNamingStrategy(LowerCaseWithUnderscores) enable , Is there any way to fixe or enhance

**Comment by taowen** [comment]
you can implement your own SetNamingStrategy, the extra package is for demonstration purpose, the core library can be extended in your own way.
