### ISSUE TITLE
invalid pc-encoded table panic

### ISSUE THREAD

**Issue by wgliang** [json-iterator/go#300]
runtime: invalid pc-encoded table f=XXX/vendor/github.com/json-iterator/go.(*Iterator).skipNumber pc=0x843235 targetpc=0x843236 tab=[0/0]0x0
        value=0 until pc=0x8431e3
        value=24 until pc=0x84320d
        value=0 until pc=0x84320e
        value=24 until pc=0x84322e
        value=0 until pc=0x843235
fatal error: invalid runtime symbol table

goroutine 0 [idle]:
runtime: unexpected return pc for runtime.sigreturn called from 0x1
stack: frame={sp:0xc420061ac0, fp:0xc420061ac8} stack=[0xc42005a000,0xc420062000)
000000c4200619c0:  000000c420061bf0  000000c420061ac0
000000c4200619d0:  000000c420000480  0000000000000000
000000c4200619e0:  0000000000000000  0000000000000000
000000c4200619f0:  0000000000000000  0000000000000000
000000c420061a00:  0000000000000000  0000000000000000
000000c420061a10:  000000c420000480  0000000000000000
000000c420061a20:  0000000000000000  0000000000000000
000000c420061a30:  0000000000000000  0000000000000000
000000c420061a40:  0000000000000000  0000000000000000
000000c420061a50:  0000000000000000  000000c420061ab0
000000c420061a60:  000000000045acc3 <runtime.sigtramp+67>  000000000000001b
000000c420061a70:  000000c420061bf0  000000c420061ac0
000000c420061a80:  0000000000000000  0000000000000011
000000c420061a90:  00000000000000f1  000000000042f4b0 <runtime.mstart+0>
000000c420061aa0:  000000c420061ab0  0000000000000006
000000c420061ab0:  000000c420067f20  000000000045adb0 <runtime.sigreturn+0>
000000c420061ac0: <0000000000000001 >0000000000000000
000000c420061ad0:  000000c42005a000  0000000000000000
000000c420061ae0:  0000000000008000  0000000000000000
000000c420061af0:  0000000000843236 <XXX/vendor/github.com/json-iterator/go.(*Iterator).skipNumber+102>  0000000000000000
000000c420061b00:  0000000000000246  000000000042f4b0 <runtime.mstart+0>
000000c420061b10:  00000000000000f1  0000000000000011
000000c420061b20:  0000000000000000  0000000000000001
000000c420061b30:  000000c420067f10  000000c420067f20
000000c420061b40:  0000000000000006  0000000000000000
000000c420061b50:  0000000000843236 <XXX/vendor/github.com/json-iterator/go.(*Iterator).skipNumber+102>  00007ffcf83b36c2
000000c420061b60:  000000c420067f10  000000000045ab67 <runtime.nanotime+71>
000000c420061b70:  0000000000000206  0000000000000033
000000c420061b80:  0000000000000000  0000000000000000
000000c420061b90:  0000000000000000  0000000000000000
000000c420061ba0:  000000c420061c80  0000000000000000
000000c420061bb0:  0000000000000000  0000000000000000
000000c420061bc0:  0000000000000000
runtime.throw(0xfaf3ae, 0x1c)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:616 +0x81
runtime.pcvalue(0x1301e58, 0x154efe0, 0x243da5, 0x843236, 0xc420061498, 0x1, 0x0)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/symtab.go:790 +0x529
runtime.funcspdelta(0x1301e58, 0x154efe0, 0x843236, 0xc420061498, 0x0)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/symtab.go:842 +0x5f
runtime.gentraceback(0x45ab67, 0xc420067f10, 0x0, 0xc420000480, 0x0, 0xc4200616f8, 0x40, 0x0, 0x0, 0x6, ...)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/traceback.go:204 +0x17e1
runtime.sigprof(0x45ab67, 0xc420067f10, 0x0, 0xc420000480, 0xc420058000)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:3712 +0x3e9
runtime.sighandler(0xc40000001b, 0xc420061bf0, 0xc420061ac0, 0xc420000480)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/signal_sighandler.go:33 +0x678
runtime.sigtrampgo(0x1b, 0xc420061bf0, 0xc420061ac0)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/signal_unix.go:349 +0x21c
runtime.sigtramp(0x1, 0x0, 0xc42005a000, 0x0, 0x8000, 0x0, 0x843236, 0x0, 0x246, 0x42f4b0, ...)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/sys_linux_amd64.s:352 +0x43
runtime: unexpected return pc for runtime.sigreturn called from 0x1
stack: frame={sp:0xc420061ac0, fp:0xc420061ac8} stack=[0xc42005a000,0xc420062000)
000000c4200619c0:  000000c420061bf0  000000c420061ac0
000000c4200619d0:  000000c420000480  0000000000000000
000000c4200619e0:  0000000000000000  0000000000000000
000000c4200619f0:  0000000000000000  0000000000000000
000000c420061a00:  0000000000000000  0000000000000000
000000c420061a10:  000000c420000480  0000000000000000
000000c420061a20:  0000000000000000  0000000000000000
000000c420061a30:  0000000000000000  0000000000000000
000000c420061a40:  0000000000000000  0000000000000000
000000c420061a50:  0000000000000000  000000c420061ab0
000000c420061a60:  000000000045acc3 <runtime.sigtramp+67>  000000000000001b
000000c420061a70:  000000c420061bf0  000000c420061ac0
000000c420061a80:  0000000000000000  0000000000000011
000000c420061a90:  00000000000000f1  000000000042f4b0 <runtime.mstart+0>
000000c420061aa0:  000000c420061ab0  0000000000000006
000000c420061ab0:  000000c420067f20  000000000045adb0 <runtime.sigreturn+0>
000000c420061ac0: <0000000000000001 >0000000000000000
000000c420061ad0:  000000c42005a000  0000000000000000
000000c420061ae0:  0000000000008000  0000000000000000
000000c420061af0:  0000000000843236 <XXX/vendor/github.com/json-iterator/go.(*Iterator).skipNumber+102>  0000000000000000
000000c420061b00:  0000000000000246  000000000042f4b0 <runtime.mstart+0>
000000c420061b10:  00000000000000f1  0000000000000011
000000c420061b20:  0000000000000000  0000000000000001
000000c420061b30:  000000c420067f10  000000c420067f20
000000c420061b40:  0000000000000006  0000000000000000
000000c420061b50:  0000000000843236 <XXX/vendor/github.com/json-iterator/go.(*Iterator).skipNumber+102>  00007ffcf83b36c2
000000c420061b60:  000000c420067f10  000000000045ab67 <runtime.nanotime+71>
000000c420061b70:  0000000000000206  0000000000000033
000000c420061b80:  0000000000000000  0000000000000000
000000c420061b90:  0000000000000000  0000000000000000
000000c420061ba0:  000000c420061c80  0000000000000000
000000c420061bb0:  0000000000000000  0000000000000000
000000c420061bc0:  0000000000000000
runtime.sigreturn(0x0, 0xc42005a000, 0x0, 0x8000, 0x0, 0x843236, 0x0, 0x246, 0x42f4b0, 0xf1, ...)
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/sys_linux_amd64.s:444

**Comment by taowen** [comment]
can this problem be reproduced by sample code?

**Comment by wgliang** [comment]
Not sure, this is a rare problem.

**Comment by vishwaspai** [comment]
Started facing this problem recently (no specific reproducible code). 
Go version: 1.10.5
Linux x86_64

<context.(*cancelCtx).String+173> function (in the stack trace below) is not the same every time. Some times it is gob encoding or json decoding or something else.

==

runtime: invalid pc-encoded table f=context.(*cancelCtx).String pc=0x531ff5 targetpc=0x531ffd tab=[0/0]0x0
        value=0 until pc=0x531f67
        value=80 until pc=0x531fea
        value=0 until pc=0x531ff5
fatal error: invalid runtime symbol table

goroutine 0 [idle]:
runtime: unexpected return pc for runtime.sigreturn called from 0x0
stack: frame={sp:0xc420047c40, fp:0xc420047c48} stack=[0xc420040000,0xc420048000)
000000c420047b40:  000000c420047d70  000000c420047c40
000000c420047b50:  000000c420000480  0000000000000000
000000c420047b60:  0000000000000000  0000000000000000
000000c420047b70:  0000000000000000  0000000000000000
000000c420047b80:  0000000000000000  0000000000000000
000000c420047b90:  000000c420000480  0000000000000000
000000c420047ba0:  0000000000000000  0000000000000000
000000c420047bb0:  0000000000000000  0000000000000000
000000c420047bc0:  0000000000000000  0000000000000000
000000c420047bd0:  0000000000000000  000000c420047c30
000000c420047be0:  00000000004595d3 <runtime.sigtramp+67>  000000000000001b
000000c420047bf0:  000000c420047d70  000000c420047c40
000000c420047c00:  0000000000000000  0000000000000011
000000c420047c10:  00000000000000f1  000000000042f1a0 <runtime.mstart+0>
000000c420047c20:  000000c420047c30  0000000000000000
000000c420047c30:  000000c42004dec0  00000000004596c0 <runtime.sigreturn+0>
000000c420047c40: <0000000000000000 >0000000000000000
000000c420047c50:  000000c420040000  0000000000000000
000000c420047c60:  0000000000008000  0000000000531ffd <context.(*cancelCtx).String+173>
000000c420047c70:  0000000000000000  0000000000000000
000000c420047c80:  0000000000000000  000000000042f1a0 <runtime.mstart+0>
000000c420047c90:  00000000000000f1  0000000000000011
000000c420047ca0:  0000000000000000  0000000000000001
000000c420047cb0:  000000c42004deb0  000000c42004dec0
000000c420047cc0:  0000000000000000  0000000000000000
000000c420047cd0:  0000000000000000  0000000000000018
000000c420047ce0:  000000c42004deb0  0000000000459473 <runtime.nanotime+67>
000000c420047cf0:  0000000000000246  0000000000000033
000000c420047d00:  0000000000000000  0000000000000000
000000c420047d10:  0000000000000000  0000000000000000
000000c420047d20:  000000c420047e00  0000000000000000
000000c420047d30:  0000000000000000  0000000000000000
000000c420047d40:  0000000000000000
runtime.throw(0xbc8c77, 0x1c)
        /usr/local/go1.10.5/go/src/runtime/panic.go:616 +0x81
runtime.pcvalue(0xd4d640, 0xfbc1c0, 0xd1b3d, 0x531ffd, 0xc420047618, 0x1, 0x0)
        /usr/local/go1.10.5/go/src/runtime/symtab.go:790 +0x529
runtime.funcspdelta(0xd4d640, 0xfbc1c0, 0x531ffd, 0xc420047618, 0x0)
        /usr/local/go1.10.5/go/src/runtime/symtab.go:842 +0x5f
runtime.gentraceback(0x459473, 0xc42004deb0, 0x0, 0xc420000480, 0x0, 0xc420047878, 0x40, 0x0, 0x0, 0x6, ...)
        /usr/local/go1.10.5/go/src/runtime/traceback.go:204 +0x17e1
runtime.sigprof(0x459473, 0xc42004deb0, 0x0, 0xc420000480, 0xc42003e000)
        /usr/local/go1.10.5/go/src/runtime/proc.go:3712 +0x3e9
runtime.sighandler(0xc40000001b, 0xc420047d70, 0xc420047c40, 0xc420000480)
        /usr/local/go1.10.5/go/src/runtime/signal_sighandler.go:33 +0x678
runtime.sigtrampgo(0x1b, 0xc420047d70, 0xc420047c40)
        /usr/local/go1.10.5/go/src/runtime/signal_unix.go:349 +0x21c
runtime.sigtramp(0x0, 0x0, 0xc420040000, 0x0, 0x8000, 0x531ffd, 0x0, 0x0, 0x0, 0x42f1a0, ...)
        /usr/local/go1.10.5/go/src/runtime/sys_linux_amd64.s:352 +0x43
runtime: unexpected return pc for runtime.sigreturn called from 0x0
stack: frame={sp:0xc420047c40, fp:0xc420047c48} stack=[0xc420040000,0xc420048000)
000000c420047b40:  000000c420047d70  000000c420047c40
000000c420047b50:  000000c420000480  0000000000000000
000000c420047b60:  0000000000000000  0000000000000000
000000c420047b70:  0000000000000000  0000000000000000
000000c420047b80:  0000000000000000  0000000000000000
000000c420047b90:  000000c420000480  0000000000000000
000000c420047ba0:  0000000000000000  0000000000000000
000000c420047bb0:  0000000000000000  0000000000000000
000000c420047bc0:  0000000000000000  0000000000000000
000000c420047bd0:  0000000000000000  000000c420047c30
000000c420047be0:  00000000004595d3 <runtime.sigtramp+67>  000000000000001b
000000c420047bf0:  000000c420047d70  000000c420047c40
000000c420047c00:  0000000000000000  0000000000000011
000000c420047c10:  00000000000000f1  000000000042f1a0 <runtime.mstart+0>
000000c420047c20:  000000c420047c30  0000000000000000
000000c420047c30:  000000c42004dec0  00000000004596c0 <runtime.sigreturn+0>
000000c420047c40: <0000000000000000 >0000000000000000
000000c420047c50:  000000c420040000  0000000000000000
**000000c420047c60:  0000000000008000  0000000000531ffd <context.(*cancelCtx).String+173>**
000000c420047c70:  0000000000000000  0000000000000000
000000c420047c80:  0000000000000000  000000000042f1a0 <runtime.mstart+0>
000000c420047c90:  00000000000000f1  0000000000000011
000000c420047ca0:  0000000000000000  0000000000000001
000000c420047cb0:  000000c42004deb0  000000c42004dec0
000000c420047cc0:  0000000000000000  0000000000000000
000000c420047cd0:  0000000000000000  0000000000000018
000000c420047ce0:  000000c42004deb0  0000000000459473 <runtime.nanotime+67>
000000c420047cf0:  0000000000000246  0000000000000033
000000c420047d00:  0000000000000000  0000000000000000
000000c420047d10:  0000000000000000  0000000000000000
000000c420047d20:  000000c420047e00  0000000000000000
000000c420047d30:  0000000000000000  0000000000000000
000000c420047d40:  0000000000000000
runtime.sigreturn(0x0, 0xc420040000, 0x0, 0x8000, 0x531ffd, 0x0, 0x0, 0x0, 0x42f1a0, 0xf1, ...)
        /usr/local/go1.10.5/go/src/runtime/sys_linux_amd64.s:444
