### ISSUE TITLE
should i custom fieldname default mapping rule？（without tags）

### ISSUE THREAD

**Issue by wardenlym** [json-iterator/go#302]
i want to custom all fieldname in no tagged struct map to “firstLowerCaseForm”，what should i do? 

for example

```
type GuestBindInfo struct {
	PhoneNumber string
	VerifyCode  string
}

to:

{"phoneNumber":"","verifyCode",""}

```

detail:

i don`t know how to extend the field name mapping behavior , if somewhere can inject callback for extensionable will fit my case, please let me know ,many thanks.

**Comment by taowen** [comment]
use https://github.com/json-iterator/go/blob/master/extra/naming_strategy.go as the demo to write your own extension
