### ISSUE TITLE
不得不吐槽一下，性能确实可以。有个巨坑真是差点放弃这个库

### ISSUE THREAD

**Issue by xiaogaofudao** [json-iterator/go#310]
听同事说这个json 库性能不错，看star 还不少也没多测试，就直接把项目的 官方json 替换了。谁知道埋了一个大坑。项目的一个json 配置文件解析出现了 重大 bug。实体类是自动生成的。也忘记排查字段的数据类型。有个字段的类型实体类 写的 是 int。项目刚开始没问题。中间有人把其中数组的一个数值 改为了 浮点型。其他都是int。解析这个数组 一直是 nil。这个问题排查了好久。最终发现是 数据类型不对。也希望遇到问题不能解析的 可以从数据类型上排查一下，是不是后期数据有变动

**Comment by taowen** [comment]
官方库也不报错呀
