### ISSUE TITLE
文档严重缺失

### ISSUE THREAD

**Issue by libra1010** [json-iterator/go#312]
效率没有测试,不过文档太少了
{"status":"error", "code":100}
type Result struct {
  Status string
 code string
}

因为code 可能会有第三方其他api,所以可能为字符串
所以希望扩展处理一下,
jsoniter.RegisterTypeDecoderFunc("string", func(ptr unsafe.Pointer, iter *jsoniter.Iterator) {
	
})

没有获取当前字段名的办法,另外怎么设置过去喃?

UnmarshalJSON 的方法签名在哪里可以看见呀,都好难找啊.文档等同于没有

**Comment by taowen** [comment]
https://github.com/json-iterator/go/blob/master/extension_tests/extension_test.go

Test_customize_field_by_extension
