### ISSUE TITLE
Dynamic json parsing

### ISSUE THREAD

**Issue by nikolas7892** [json-iterator/go#314]
I'm working with an endpoint that is subject to dynamic updates in key and value pairs. What is the most efficient way to parse a nested json object in a json array without knowing the exact key, but knowing potential value characters? I had in mind to iterate over values and simply use switch / if clauses to match contained characters by key value until reaching the nested object. Is that the ideal solution?

**Comment by taowen** [comment]
if the key is not fixed, you have to parse it into a map, and iterate the keys in runtime
