### ISSUE TITLE
Try to remove item in array but still left {}, in final json string.

### ISSUE THREAD

**Issue by hobbytp** [json-iterator/go#318]
## Problem
Marshal function will not remove empty array item and left "{},"

## Description
My test code is as below:
```
type Service struct { 
    Name string `json:"name,omitempty"`
    ID string      `json:"ID,omitempty"`
}

type Profile struct {
    NfServices    []Service `json:"nfServices,omitempty"`
}

func RemoveStructFromJson(){
    data := []byte(`{"nfServices":[{"name":"Hobby","ID": "111"},{"name": "Mindy","ID": "222"}]}`)

    var nfProfile Profile 
    var jsoniter = jsoniter.ConfigCompatibleWithStandardLibrary
    var  tmp Service 
    err := jsoniter.Unmarshal(data, &nfProfile)
    if err != nil {
        fmt.Println(err)
    }

    fmt.Println(nfProfile)
    nfProfile.NfServices[0] =  tmp   //==>I want to remove the Service here, so assign tmp here.
    result, err := jsoniter.Marshal(nfProfile)
    if err != nil {
        fmt.Println(err)
    }
    fmt.Println(string(result))
}
```

My test output is as below:
-----------------------------------
{[{Hobby 111} {Mindy 222}]}
{"nfServices":[**{},**{"name":"Mindy","ID":"222"}]}  ==>I want the "{}," to be removed in final json string.

What is your comments? Thanks for your support!

**Comment by taowen** [comment]
jsoniter is compatible with json standard library. This behavior is not supported in standard library as well. You should filter out the array before marshal. You can use https://github.com/json-iterator/go/blob/master/extension_tests/extension_test.go if you really want to hook your own code in the process.
