### ISSUE TITLE
duplicate keys in json

### ISSUE THREAD

**Issue by Katsusan** [json-iterator/go#319]
when I tried to parse the json from  valve's web api, there are some duplicate keys in it.
encoding/json seems not work.  Can 'json-iterator' deal with this condition?
json example:     
    see https://github.com/Katsusan/go-dota2/blob/master/livinggames.json

```json
"abilities":[  // <-这样的"abilities"键总共有 0-5 个(代表 各个dota2英雄的技能升级情况)
{
"ability_id":5106,   //唯一技能 ID
"ability_level":2  //技能等级
},
{
"ability_id":5107,
"ability_level":3
}
]
,
"abilities":[
{
"ability_id":5082,
"ability_level":3
},
{
"ability_id":5083,
"ability_level":2
}
]
,
"abilities":[
{
"ability_id":5122,
"ability_level":3
},
{
"ability_id":5123,
"ability_level":2
},
{
"ability_id":5125,
"ability_level":1
}
]
```

**Comment by AllenX2018** [comment]
What's the expected unmarshall behavior? IMO, the json string in your example is invalid. According to RFC 7159/8259, chapter 4, ```The names within an object SHOULD be unique.```

**Comment by Katsusan** [comment]
@AllenX2018 ,yeah, later I have checked this condition in RFC，and as your last replay said, “The names within an object SHOULD be unique.”，the RFC uses "SHOULD" here。
When you grep “must” in this RFC, you will find there are some "must" cases. for example:
[chapter 3]
"A JSON value MUST be an object, array, number, or string, or one of the following three literal names".
"The literal names MUST be lowercase."   

so I thought duplicate keys in json is advised to be avoided but it's not mandatory.
(maybe Valve doesn't see it as invalid json.)

As to the expected unmarshall behavior, 
```Go
type Resp struct {
    abilities  [][]string `json:"ability"
}
``` 
the two-dimension slice above may handle this condition.
```json
{
    "ability" : ["abilityA", "abilityB"],
    "ability" : ["abilityC", "abilityD"],
}
```

**Comment by AllenX2018** [comment]
> As to the expected unmarshall behavior,
> 
> ```go
> type Resp struct {
>     abilities  [][]string `json:"ability"
> }
> ```
> 
> the two-dimension slice above may handle this condition.
> 
> ```json
> {
>     "ability" : ["abilityA", "abilityB"],
>     "ability" : ["abilityC", "abilityD"],
> }
> ```

For your testcase, in order to unmarshall to the ```Resp``` struct, your input json string should be like
```json
{"ability":[["abilityA","abilityB"],["abilityC","abilityD"]]}
```

However, it seems the input json is out of your control. So the workround is to register a field decoder like this:
```go
func workaround() {
	var testResp Resp
	jsoniter.RegisterFieldDecoderFunc(reflect.TypeOf(testResp).String(), "Abilities",
		func(ptr unsafe.Pointer, iter *jsoniter.Iterator){
			var strArr []string
			any := iter.ReadAny()
			any.ToVal(&strArr)
			arrayPtr := (*[][]string)(ptr)
			*arrayPtr = append(*arrayPtr, strArr)
		})
	if err := jsoniter.UnmarshalFromString(`{"ability":["abilityA", "abilityB"], "ability":["abilityC", "abilityD"]}`,
		&testResp); err == nil{
		fmt.Println(testResp)
		// {[[abilityA abilityB] [abilityC abilityD]]}
	}
}
```

Though I still don't think the input json is valid in your testcase

**Comment by Katsusan** [comment]
@AllenX2018 well, Can jsoniter.RegisterFieldDecoderFunc work correctly? I tried log output and setting breakpoints, neither of them showed DecodeFunc has been called.

And in https://github.com/json-iterator/go/blob/49c900ee46e6efa73ea31a4eef029bc0a19a1ed9/extension_tests/decoder_test.go#L83-L96 RegisterFieldDecoderFunc also seems not working.
In the unit test the result tom should be Tom{field: "100"} but it turned out to be Tom{}.

**Comment by AllenX2018** [comment]
1. If you want your struct's field to be encoded/decoded, it should be exported. Private field, like the ```field1``` in your ```Tom``` struct, will not be encoded/decoded. In other word, it should be ```Field1```, not ```field1```
2. Are you sure the type string of your ```Tom``` struct is ```"jsoniter.Tom"```? If you're not sure, you'd better use reflect to get it's type string and do not hardcode it explicitly.

So for your testcase, it should be like:
```go
func Test_customize_field_decoder(t *testing.T) { 
 	type Tom struct { 
 		Field1 string 
 	} 
        tom := Tom{} 
 	jsoniter.RegisterFieldDecoderFunc(reflect.TypeOf(tom).String(), "Field1", func(ptr unsafe.Pointer, iter *jsoniter.Iterator) { 
 		*((*string)(ptr)) = strconv.Itoa(iter.ReadInt()) 
 	}) 
 	//defer jsoniter.ConfigDefault.(*frozenConfig).cleanDecoders() 
 	err := jsoniter.Unmarshal([]byte(`{"Field1": 100}`), &tom) 
 	if err != nil { 
 		t.Fatal(err) 
 	} 
 } 
```

**Comment by Katsusan** [comment]
changed to exported format and succeeded to unmarshal it。I thought that unmarshal calling in the same package doesn't need that. 

Thanks for figuring out this!
