### ISSUE TITLE
cannot omit interface null

### ISSUE THREAD

**Issue by w-zz** [json-iterator/go#334]
```
var S struct {
	T interface{} `json:"t,omitempty"`
	V int         `json:"v"`
}
ji := jsoniter.ConfigCompatibleWithStandardLibrary
j, _ := ji.Marshal(S)
fmt.Println(string(j))

j2, _ := json.Marshal(S)
fmt.Println(string(j2))
```
output is
```
{"t":null,"v":0}
{"v":0}
```
encoding/json can omit null value, jsoniter's behavior is not same.I want to ask if this is a bug of not. if I want to omit null, how can I do.

**Comment by AllenX2018** [comment]
Can not reproduce, I think this issue has been fixed in the latest version.
