### ISSUE TITLE
Can Encoder add EmitDefault option?

### ISSUE THREAD

**Issue by xyz347** [json-iterator/go#347]
I want to ignore "omitempty" tag. like [jsonpb.Marshaler](https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler)

I want to do this because [grpc add omitempty to every filed default](https://stackoverflow.com/a/50044963/5845104)  but jsonpb marshal int64 to string

**Comment by taowen** [comment]
should be done via extension instead of new option

**Comment by xyz347** [comment]
实在不好意思，我还是用中文吧，不然问题描述不清。提issue之前看了gdoc，也留意到了那几个register函数和extension，但是苦于网上和代码里面都没有例子。而且从函数的参数来看感觉extension是针对特定的type的，而且是全局的。而我的情况是:  

func a (x interface{}) {
// 序列化x的时候，x的所有变量都不忽略缺省值
}

func b(x interface{}){
// 序列化x的时候，忽略缺省值
}

如果需要实现这种功能，应该怎么用extension

**Comment by taowen** [comment]
可以创建两个config实例，各自使用不同的extension。然后a和b使用不同的实例去调用序列化和反序列化

https://github.com/json-iterator/go/blob/master/extension_tests/extension_test.go

```go
cfg := jsoniter.Config{}.Froze()
	cfg.RegisterExtension(&testExtension{})
	obj := TestObject1{}
	err := cfg.UnmarshalFromString(`{"field-1": 100}`, &obj)
```
