### ISSUE TITLE
json编码出现如下错误

### ISSUE THREAD

**Issue by jilieryuyi** [json-iterator/go#370]
%!B(MISSING)%!B(MISSING)%!M(MISSING)
这个是什么东西呢 ？ %!B(MISSING)

**Comment by cupen** [comment]
@jilieryuyi  最好有一个可重现的例子，否则再怎么哭喊也没人能帮你。
只看你贴出来的东西，无责任猜测是调用 `fmt.Sprintf`但没给参数产生的。
