### ISSUE TITLE
Wrong result of jsoniter.Valid()

### ISSUE THREAD

**Issue by CharlesGe129** [json-iterator/go#377]
For those two strings, jsoniter.Valid() function would return True while neither of two strings is of valid JSON format. Related source code is located at line 48 of file /json-iterator/go/iter_skip_strict.go, the "switch-case". My Golang version is 1.12.5, and I'm using the latest version of jsoniter package. Here are the codes:

`data := "404 Not Found"`
`fmt.Println(jsoniter.Valid([]byte(data)))`
`data = "{}123"`
`fmt.Println(jsoniter.Valid([]byte(data)))`

**Comment by xwi88** [comment]
I also have the same issue, ref: https://github.com/xwi88/kit4go/blob/v0.0.0/json/json_test.go .
I guess that the jsoniter can only valid the {}, ignore after characters.
ex: 
True
- {Blog:"xwi88", Name:"https://github.com/xwi88"}
- {Blog:"xwi88", Name:"https://github.com/xwi88"}0@

False
- 0{Blog:"xwi88", Name:"https://github.com/xwi88"}@
- `{Blog:"xwi88", Name:"https://github.com/xwi88"}`
