### ISSUE TITLE
Need help:Why my code made an error?

### ISSUE THREAD

**Issue by Smityz** [json-iterator/go#379]
```
type b struct{
	Result string   `json:result`
	Error_info string   `json:error_info`
	Level string   `json:level`
	Score string   `json:score`
}
```
here is my struct
`{"_idip_msg_id_":["7884_1560700537_9.68.233.159_6693_1046452841"],"result":["0"],"error_info":[""],"level":["1"],"score":["100"],"_idip_req_id_":["2"]}`
And here is my json
But error says
`main.b.Level: ReadString: expects " or n, but found [, error found in #10 byte of ...|{"Level":["1"],"Scor|..., bigger context ...|{"Level":["1"],"Score":["100"],"_idip_req_id_":["2"],"_idip_|... `
What's wrong with my code

**Comment by cupen** [comment]
en..... could you put your code here?

**Comment by jxww** [comment]
It looks like your struct does not match your json string. I think the following struct may work.

```
type b struct{
	Result []string   `json:result`
	Error_info []string   `json:error_info`
	Level []string   `json:level`
	Score []string   `json:score`
}
```

**Comment by AllenX2018** [comment]
@jxww   You are right, of course, the following json string also works.

{"_idip_msg_id_":"7884_1560700537_9.68.233.159_6693_1046452841","result":"0","error_info":"","level":"1","score":"100","_idip_req_id_":"2"}
