### ISSUE TITLE
panic: concurrent map writes in reflect_extension.go:205

### ISSUE THREAD

**Issue by kangkang66** [json-iterator/go#383]
**used by:**
extra.RegisterFuzzyDecoders()
err = jsoniter.Unmarshal(params,adPlatform)

**panic:**
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 18778 [running]:
runtime.throw(0xf4a995, 0x15)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000325180 sp=0xc000325150 pc=0x42d812
runtime.mapassign_faststr(0xddbb20, 0xc000187380, 0xf3f31a, 0x6, 0x0)
/usr/local/go/src/runtime/map_faststr.go:291 +0x40f fp=0xc0003251e8 sp=0xc000325180 pc=0x412f2f
github.com/json-iterator/go.RegisterTypeDecoder(...)
/Users/hankangkang/go/pkg/mod/github.com/json-iterator/go@v1.1.6/reflect_extension.go:205
github.com/json-iterator/go/extra.RegisterFuzzyDecoders()
/Users/hankangkang/go/pkg/mod/github.com/json-iterator/go@v1.1.6/extra/fuzzy_decoder.go:23 +0xd9 fp=0xc000325260 sp=0xc0003251e8 pc=0xcfe209
chubao/internal/api.RouteHandle.AdvertiseConf(0xc000115980, 0xc0001159c0, 0xc0001bc790)
/Users/hankangkang/go/src/chubao/internal/api/route.go:88 +0xc07 fp=0xc000325560 sp=0xc000325260 pc=0xd01937
chubao/internal/api.RouteHandle.AdvertiseConf-fm(0xc0001bc790)
/Users/hankangkang/go/src/chubao/internal/api/route.go:67 +0x3d fp=0xc000325588 sp=0xc000325560 pc=0xd033cd
github.com/gin-gonic/gin.(*Context).Next(0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a fp=0xc0003255a0 sp=0xc000325588 pc=0xb1494a
chubao/internal/api.MiddlewareHandle.ResponseEqualMiddleware.func1(0xc0001bc790)
/Users/hankangkang/go/src/chubao/internal/api/middleware.go:49 +0x35a fp=0xc0003256f8 sp=0xc0003255a0 pc=0xd02d3a
github.com/gin-gonic/gin.(*Context).Next(0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a fp=0xc000325710 sp=0xc0003256f8 pc=0xb1494a
chubao/internal/api.MiddlewareHandle.AuthTokenMiddleware.func1(0xc0001bc790)
/Users/hankangkang/go/src/chubao/internal/api/middleware.go:64 +0xc0 fp=0xc000325790 sp=0xc000325710 pc=0xd02e80
github.com/gin-gonic/gin.(*Context).Next(0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a fp=0xc0003257a8 sp=0xc000325790 pc=0xb1494a
chubao/internal/api.MiddlewareHandle.RequestIdMiddleware.func1(0xc0001bc790)
/Users/hankangkang/go/src/chubao/internal/api/middleware.go:29 +0x2ca fp=0xc000325858 sp=0xc0003257a8 pc=0xd0292a
github.com/gin-gonic/gin.(*Context).Next(0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a fp=0xc000325870 sp=0xc000325858 pc=0xb1494a
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/recovery.go:83 +0x5a fp=0xc0003258a0 sp=0xc000325870 pc=0xb27c1a
github.com/gin-gonic/gin.(*Context).Next(0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a fp=0xc0003258b8 sp=0xc0003258a0 pc=0xb1494a
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/logger.go:240 +0xe1 fp=0xc000325a58 sp=0xc0003258b8 pc=0xb26cc1
github.com/gin-gonic/gin.(*Context).Next(0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3a fp=0xc000325a70 sp=0xc000325a58 pc=0xb1494a
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0002caea0, 0xc0001bc790)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 +0x5b2 fp=0xc000325b58 sp=0xc000325a70 pc=0xb1e162
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0002caea0, 0x10be300, 0xc0006c0360, 0xc0001d0500)
/Users/hankangkang/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 +0x134 fp=0xc000325b90 sp=0xc000325b58 pc=0xb1d994
net/http.(*ServeMux).ServeHTTP(0xc0000c2100, 0x10be300, 0xc0006c0360, 0xc0001d0500)
/usr/local/go/src/net/http/server.go:2375 +0x1d6 fp=0xc000325bf0 sp=0xc000325b90 pc=0x73a316
cootek.com/elete/sdk.(*httpHandlerWrap).ServeHTTP(0x184c378, 0x10c0c00, 0xc0003a80e0, 0xc0001d0400)
/Users/hankangkang/go/src/cootek.com/elete/sdk/http.go:85 +0x489 fp=0xc000325cf0 sp=0xc000325bf0 pc=0x9056f9
net/http.serverHandler.ServeHTTP(0xc00018d790, 0x10c0c00, 0xc0003a80e0, 0xc0001d0400)
/usr/local/go/src/net/http/server.go:2774 +0xa8 fp=0xc000325d20 sp=0xc000325cf0 pc=0x73b6e8
net/http.(*conn).serve(0xc0000fe8c0, 0x10c3a40, 0xc0006aa640)
/usr/local/go/src/net/http/server.go:1878 +0x851 fp=0xc000325fc8 sp=0xc000325d20 pc=0x737281
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000325fd0 sp=0xc000325fc8 pc=0x45ca51
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by kangkang66** [comment]
用法错误

**Comment by sunnyyellow** [comment]
怎么解这个问题呢，我也遇到了。 是不是extra.RegisterFuzzyDecoders()初始化一次就可以了？
目前项目里的代码是每次来请求就会调用一次 extra.RegisterFuzzyDecoders()，并发一上来就panic了。

**Comment by AllenX2018** [comment]
只需要初始化的时候调一次
