### ISSUE TITLE
Please tag a new release with go.mod in it

### ISSUE THREAD

**Issue by jfesler** [json-iterator/go#391]
I'm having to explicitly pull from "master" instead of "latest" or "v1.16" since that latest release does not have go.mod committed yet.   Otherwise, dependencies are not handled well, and downstream users of my modules have to use "replace" commands to work around the lack of version data on the modules you depend on; in particular github.com/modern-go/concurrent.

Thanks for the module.

**Comment by taowen** [comment]
https://github.com/json-iterator/go/releases/tag/v1.1.7
