### ISSUE TITLE
encode interface to json not found in golang version

### ISSUE THREAD

**Issue by tqyq** [json-iterator/go#4]
Hi,
I'd try encode map into json string but not found such sample or test code.
Since a critical bug of json.Marshal(map) in go version 1.7, I wanna try jsoniter.
Thanks.

**Comment by taowen** [comment]
json encoder for the golang version has not been provided yet. I am working on that.

**Comment by hanbang-wang** [comment]
@taowen what's your progress now, I may can help you with that.

**Comment by taowen** [comment]
@hanbang-wang go ahead, I have already written the java version https://github.com/json-iterator/java/tree/master/src/main/java/com/jsoniter/output It will be simple to translate to golang
