### ISSUE TITLE
区分大小写问题

### ISSUE THREAD

**Issue by lixy529** [json-iterator/go#402]
我在go1.12.9里测试，如果结构体成员超过10，json的key就区分大小写。

**Comment by lixy529** [comment]
`type StTest struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
	Cpid string `json:"cpId"`
	VId1 string `json:"vId1"`
	VId2 string `json:"vId2"`
	VId3 string `json:"vId3"`
	VId4 string `json:"vId4"`
	VId5 string `json:"vId5"`
	VId6 string `json:"vId6"`
	VId7 string `json:"vId7"`
	VId8 string `json:"vId8"`
}

func main() {
	str := `{"NAME":"lixy", "AGE":18, "CPID":"1111"}`
	st := StTest{}
	err := json.Unmarshal([]byte(str), &st)
	fmt.Printf("%+v\n", st)
	fmt.Println(err)
}`

只要我把VId8注释掉就没有问题，否则解析不到值

**Comment by lixy529** [comment]
应该是结构体里的字段超过10个，就会区分大小。

**Comment by AllenX2018** [comment]
@lixy529  使用当前最新版本的验证,这个issue已经不存在了
