### ISSUE TITLE
Feature - Callback OnFieldUnmarshalled

### ISSUE THREAD

**Issue by eduarhasanaj** [json-iterator/go#444]
Hi,
I am trying to create a parser for flat models where I keep track of unmarshalled columns.
My first approach wast to use iterator but it has a + 500 - 600 ns overhead.
After that i tried Decoder and the overhead dropped.
I am not happy with the performance as it is 5x slower than just decoding.
Is there any possibility to extend Decoder so each time it decodes a property it sends back the name of that property?

**Comment by AllenX2018** [comment]
Do you call `iter.ReadMapCB` to get every field's name string of your struct while parsing? I think that's the only way to get the field's name string while parsing. Maybe you can try `Any.Keys()`, though I don't think it will be faster than using iterator directly.

**Comment by eduarhasanaj** [comment]
@AllenX2018  thanks for the reply
The code that uses the Iterator is slower.
Here is a sample of it
````
it := jsoniter.Parse(jsoniter.ConfigDefault, r.Body, 64)
	if it.Error != nil {
		return nil, it.Error
	}

	bindingMap := bindingMaps[t.Type()]
	columns := make([]string, 0, len(bindingMap))
	key := it.ReadObject()
	if it.Error != nil {
		return nil, it.Error
	}

	for key != "" {
		valType := it.WhatIsNext()
		if valType == jsoniter.ObjectValue || valType == jsoniter.ArrayValue {
			return nil, errors.New("ParseModel supports only flat object model")
		}

		fIndex, ok := bindingMap[key]
		if !ok {
			return nil, errors.New("could not bind to model: key " + key)
		}

		it.ReadVal(t.Field(fIndex).Addr().Interface())
		if it.Error != nil {
			return nil, errors.New("could not bind to model")
		}

		columns = append(columns, key)

		key = it.ReadObject()
		if it.Error != nil {
			return nil, it.Error
		}
	}

	return columns, nil
````

The version with decoder first unmarshalls into map[string]jsoniter.RawMessage then iterates the map to unmarshall each field. Maybe this happens because the number of properties is too small (I am testing with 2 properties)

**Comment by AllenX2018** [comment]
I run some benchmark between using `iterator` and `decoder` according to your description, you can check the test case on https://play.golang.org/p/3QKtzFv4sCK. In my environment, it didn't show that using decoder is faster:

```
BenchmarkIterator-12             2485971               485 ns/op             336 B/op          8 allocs/op
BenchmarkDecoder-12               923878              1289 ns/op            1360 B/op         18 allocs/op
```

**Comment by eduarhasanaj** [comment]
@AllenX2018 Thanks for your time. My aim was to test only a method in a http handler and due to inexperience I am doing it wrong

```
//Benchmark test before when decoder was fast
handler := func(w http.ResponseWriter, r *http.Request) {
		for i := 0; i < b.N; i++ {
			bop := New(w, r)
			var m model
			bop.ParseModel(&m)
		}
	}

//New way of testing where iterator is faster
for i := 0; i < b.N; i++ {
		r := httptest.NewRequest("POST", "http://example.com/foo", bytes.NewReader(json))
		r.Header.Add("Content-Type", "application/json")
		r.Header.Add("Content-Length", strconv.Itoa(len(json)))

		w := httptest.NewRecorder()
		handler(w, r)
}
```

Is there any way to test just the block inside handler?

**Comment by eduarhasanaj** [comment]
I am closing this as it seems that testing was not correct.
Thanks again for your time @AllenX2018
