### ISSUE TITLE
Is it a bug  for parsing "\\" string ?

### ISSUE THREAD

**Issue by 1046102779** [json-iterator/go#46]
Is it a bug ?
![image](https://user-images.githubusercontent.com/20457624/26934201-4dab0324-4c9b-11e7-9ff5-f0a17234ce77.png)
![image](https://user-images.githubusercontent.com/20457624/26934222-5a1a9728-4c9b-11e7-89e4-04ba72dbef3a.png)

**Comment by taowen** [comment]
this is not a bug. iter.Error will have a error in this case.
