### ISSUE TITLE
is it a bug for parsing whitespace string?

### ISSUE THREAD

**Issue by 1046102779** [json-iterator/go#47]
![image](https://user-images.githubusercontent.com/20457624/26934789-f3c8a3b4-4c9c-11e7-9b0b-da79c056cc83.png)

**Comment by Kisesy** [comment]
func main() {
		str := ` "s" `
		iter := jsoniter.ParseString(str)
		fmt.Println(iter.ReadString())
		fmt.Println(iter.Error == nil)
	}
	// s
	// true

**Comment by taowen** [comment]
this is not a bug. If input is not string, ReadString() will produce a error in the field of iter.Error.
