### ISSUE TITLE
Unpredictable behavior when unmarshaling incorrect integer

### ISSUE THREAD

**Issue by BorisKozo** [json-iterator/go#471]
This is a little strange situation albeit one that was encountered in our application.
It seems that if you try to unmarshal a floating point number into *int the behavior will be unpredictable depending on your JSON structure. In the native implementation if works fine.

Take for example this program

````
package main

import (
    "encoding/json"
    "fmt"
    jsoniter "github.com/json-iterator/go"
)

type DataStruct struct {
    Foo *string `json:"foo"`
    Bar *int    `json:"bar"`
}

func main() {
    data := `{"foo":"this is string", "bar":123.123}`
    unmarshaled := DataStruct{}
    json.Unmarshal([]byte(data), &unmarshaled)
    fmt.Printf("Build-in: foo = %s, bar = %d\n", *unmarshaled.Foo, *unmarshaled.Bar)

    unmarshaled2 := DataStruct{}
    var JsonPaser = jsoniter.ConfigCompatibleWithStandardLibrary
    JsonPaser.Unmarshal([]byte(data), &unmarshaled2)
    fmt.Printf("JSON Iter: foo = %s, bar = %d\n", *unmarshaled2.Foo, *unmarshaled2.Bar)
}
````

As it is now it will print:
````
Build-in: foo = this is string, bar = 0
JSON Iter: foo = this is string, bar = 123
````

But if you change the order of the data to:
```` data := `{"bar":123.123, "foo":"this is string"} ````
It will not be able to read "Foo" anymore
````
Build-in: foo = this is string, bar = 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x58ab68]
````

**Comment by AllenX2018** [comment]
IMO, you should check the return value when you call `Unmarshal` and if the err it returns is not nil, you should handle the error and not read the variable you pass to `Unmarshal` function.

**Comment by BorisKozo** [comment]
Ok fair enough.
