### ISSUE TITLE
Unmarshal going wrong with nested structs

### ISSUE THREAD

**Issue by gvencadze** [json-iterator/go#479]
Hi, I have the below structs in my code, and I want to unmarshal request body to them. If I use jsoniter - only ProductData.Title is populating, other data is equal to " " or "0", but if I use std encoding/json - everything is okay. My func is below structs. It would be great If somebody will help me with this issue

```code
type Product struct {
	Id        int       
	Link      string      
	Product   ProductData 
	Available bool        
	New       bool        
}
type ProductData struct {
	Title       string 
	Price       Price  
	Photo       Photo  
	Description string 
}
type Photo struct {
	Photo_200  string 
	Photo_400  string 
	Photo_1000 string 
	Photo_max  string 
}
type Price struct {
	Amount     int 
	Old_amount int 
}
```

This is my code in function
```code
body, err := ioutil.ReadAll(r.Body)
	defer r.Body.Close()
	if err != nil {
		fmt.Print(err)
		return
	}

	var requestData Product
	_ = API.Json.Unmarshal(body, &requestData) // not working
       //_ = json.Unmarshal(body, &requestData) - works as expected
```

**Comment by AllenX2018** [comment]
Can you provide the request body?

**Comment by gvencadze** [comment]
@AllenX2018 I checked my request body, and saw that I send string instead of int, that's why jsoniter get an error and stop writing data.
