### ISSUE TITLE
give developer the option to ignore struct tag "-"

### ISSUE THREAD

**Issue by surethink** [json-iterator/go#487]
I appreciate your excellent pkg, it helps me a lot. I need a new feature, please consider it,thank you!

 There is an id field in my struct, I don't want to expose this field to outside users, so I tag it with "-", it works well. 
when I  marshal  the struct  to  cache in redis and unmarshal to the struct from redis,I found that the fields I tagged with "-" are all zero values, it works well too, but that is not what I want
I hope there is an option for me to decide whether to ignore the "-" tag, when I marshal/unmarshal to cache in redis, I want to ignore the "-"tag and marshal/unmarshal all fields, when I marshal/unmarshal to frontend, the "-" works as it is now

**Comment by szyhf** [comment]
```golang
type Config struct {
	IndentionStep                 int
	MarshalFloatWith6Digits       bool
	EscapeHTML                    bool
	SortMapKeys                   bool
	UseNumber                     bool
	DisallowUnknownFields         bool
	TagKey                        string
	OnlyTaggedField               bool
	ValidateJsonRawMessage        bool
	ObjectFieldMustBeSimpleString bool
	CaseSensitive                 bool
}

// ConfigFastest marshals float with only 6 digits precision
var ConfigFastest = Config{
	EscapeHTML:                    false,
	MarshalFloatWith6Digits:       true, // will lose precession
	ObjectFieldMustBeSimpleString: true, // do not unescape object field
}.Froze()
```

config the `TagKey` option by yourself.

**Comment by surethink** [comment]
thanks for your reply.
the tagKey -  is ok for me, I don't want to change it globally.  what I really need is  when I marshall unmarshall, allow me to decide whether to ignore the tagKey

the application scenario is described in my last post

**Comment by szyhf** [comment]
> thanks for your reply.
> the tagKey - is ok for me, I don't want to change it globally. what I really need is when I marshall unmarshall, allow me to decide whether to ignore the tagKey
> 
> the application scenario is described in my last post

Oh, you didn't understand, you can just make a new and private config in you project, or a function, it will not effect the global config.

For example: 

```go
	jsoniter.Config{
		TagKey: "XXX",
	}.Froze().Marshal(v interface{})
```

**Comment by surethink** [comment]
private config in the function...  I got it!
thank you so much
