### ISSUE TITLE
当json里的value有双引号时解析出错，能解析这种情况的json吗？

### ISSUE THREAD

**Issue by hel2o** [json-iterator/go#492]
```
{
				"id": 797,
				"timestamp": 1599622843,
				"ip_addr": "192.168.99.16",
				"mac": "00:0c:29:fd:a8:56",
				"host": "cx.soft.360.cn",
				"uri": "/soft/geticon?info=[[103352,"",1]]",
				"comment": ""
			}
```
类似以上uri字段的值带有双引号的情况，目前解析是会报错

**Comment by sotex** [comment]
你这个 json 正确的写法应该是这样的吧
```json
{
	"id": 797,
	"timestamp": 1599622843,
	"ip_addr": "192.168.99.16",
	"mac": "00:0c:29:fd:a8:56",
	"host": "cx.soft.360.cn",
	"uri": "/soft/geticon?info=[[103352,\"\",1]]",
	"comment": ""
}
```
双引号需要转义。
解析报错应该是把 `"uri": "/soft/geticon?info=[[103352,"",1]]",` 当作 `"uri": "/soft/geticon?info=[[103352,"`和`",1]]",`两部分了，后面这部分只有 key 没有 value 是不行的，除非在一个数组里面。

**Comment by hel2o** [comment]
> 
> 
> 你这个 json 正确的写法应该是这样的吧
> 
> ```json
> {
> 	"id": 797,
> 	"timestamp": 1599622843,
> 	"ip_addr": "192.168.99.16",
> 	"mac": "00:0c:29:fd:a8:56",
> 	"host": "cx.soft.360.cn",
> 	"uri": "/soft/geticon?info=[[103352,\"\",1]]",
> 	"comment": ""
> }
> ```
> 
> 双引号需要转义。
> 解析报错应该是把 `"uri": "/soft/geticon?info=[[103352,"",1]]",` 当作 `"uri": "/soft/geticon?info=[[103352,"`和`",1]]",`两部分了，后面这部分只有 key 没有 value 是不行的，除非在一个数组里面。

是的，但人家返回给我的数据就这样。。。

**Comment by sotex** [comment]
> 
> 
> > 你这个 json 正确的写法应该是这样的吧
> > ```json
> > {
> > 	"id": 797,
> > 	"timestamp": 1599622843,
> > 	"ip_addr": "192.168.99.16",
> > 	"mac": "00:0c:29:fd:a8:56",
> > 	"host": "cx.soft.360.cn",
> > 	"uri": "/soft/geticon?info=[[103352,\"\",1]]",
> > 	"comment": ""
> > }
> > ```
> > 
> > 
> > 双引号需要转义。
> > 解析报错应该是把 `"uri": "/soft/geticon?info=[[103352,"",1]]",` 当作 `"uri": "/soft/geticon?info=[[103352,"`和`",1]]",`两部分了，后面这部分只有 key 没有 value 是不行的，除非在一个数组里面。
> 
> 是的，但人家返回给我的数据就这样。。。

所以，你应该找给你返回数据的那一方，让他们修正这个问题啊。他们估计这个JSON是字符串拼接出来的吧，没有处理要转义的情况。
