### ISSUE TITLE
test suite

### ISSUE THREAD

**Issue by thockin** [json-iterator/go#51]
I have a battery of tests I have been working on to prove that JSON encoders are exactly compatible with Go's standard JSON.  It doesn't pass against json-iterator yet (I filed the first bug just now), but I'd be happy to clean it up and contribute it here, if it is interesting to you to demonstrate that you're exactly compatible (and benchmark).

Before I do that work, I thought I would ask :)

**Comment by taowen** [comment]
please, much appreciated !

**Comment by thockin** [comment]
Will do.
