### ISSUE TITLE
Unmarshal result is inconsistent with the standard library

### ISSUE THREAD

**Issue by chrisyip** [json-iterator/go#515]
```go
package main

import (
	"encoding/json"
	jsoniter "github.com/json-iterator/go"
	"fmt"
)

var json2 = jsoniter.ConfigCompatibleWithStandardLibrary

func main() {
	data1 := map[string]string{}
	json.Unmarshal([]byte(`{"a":1,"b":"abc"}`), &data1)
	fmt.Println(data1) // Output map[a: b:abc]

	data2 := map[string]string{}
	json2.Unmarshal([]byte(`{"a":1,"b":"abc"}`), &data2)
	fmt.Println(data2) // Output map[a: b:abc]

	data3 := map[string]string{}
	json.Unmarshal([]byte(`{"a":12,"b":"abc"}`), &data3)
	fmt.Println(data3) // Output map[a: b:abc]

	data4 := map[string]string{}
	json2.Unmarshal([]byte(`{"a":12,"b":"abc"}`), &data4)
	fmt.Println(data4) // Output map[a:] <- key "b" is missing
}
```

**Comment by Maelkum** [comment]
All four of those Unmarshalling calls result in errors, which are ignored. So it seems you're relying on the output of failed operations and expect them to fail in the same manner.

Also, the [documentation ](https://golang.org/pkg/encoding/json/#Unmarshal)for the standard library notes:

> If a JSON value is not appropriate for a given target type, or if a JSON number overflows the target type, 
> Unmarshal skips that field and completes the unmarshaling as best it can. If no more serious errors are 
> encountered, Unmarshal returns an UnmarshalTypeError describing the earliest such error. In any case, 
> **it's not guaranteed that all the remaining fields following the problematic one will be unmarshaled into the target object.**

To me it sounds like what's in C parlance `undefined behaviour` and you should not really rely on the output of such operations.

**Comment by chrisyip** [comment]
OK, I get it. Thanks for your reply.
