### ISSUE TITLE
Automatically omit decimals when using MarshalToString

### ISSUE THREAD

**Issue by CHN-STUDENT** [json-iterator/go#522]
eg

```golang 
package main

import (
	"fmt"
	"github.com/json-iterator/go"
)

type ClientInfo struct {
	CPU float64 `json:"cpu"`
}

func NewDefaultClientInfo() ClientInfo {
	return ClientInfo {
		CPU: 0.0,
	}
}

func main() {
	var clientInfo = NewDefaultClientInfo()
	clientInfo.CPU = 12.0
	data, _ := jsoniter.MarshalToString(&clientInfo)
	fmt.Println(data)
}

```

Expected value:  `{ "CPU": 12.0 }`

Actual value:  `{ "CPU": 12 }`

I do not hope automatically omit decimals my float64 value, so could you tell me how to solve it? Thanks!

**Comment by bytegaurav** [comment]
It is a default behaviour even in encoding/json library since it treats float64 and int as JSON numbers. Read here https://golang.org/pkg/encoding/json/#Unmarshal 

To keep decimal intact, you can define your own type for float and implement MarshalJSON method on that type.

**Comment by CHN-STUDENT** [comment]
@bytegaurav ok. thanks! i define my own type json date to solve it. Glad to get your help!
