### ISSUE TITLE
`json:",omitempty"` not omitting if empty

### ISSUE THREAD

**Issue by jrapoport** [json-iterator/go#523]
```go
var json = jsoniter.ConfigCompatibleWithStandardLibrary

type Test struct {
     OmitMeIfEmpty string `json:",omitempty"`
}

test = new(Test)
json.Marshal(test)
...
```
expect:
`{}`

get:
```json
{
     "OmitMeIfEmpty": ""
}
```

`"encoding/json"` works as expected.

Not expected, but no error is returned.

**Comment by bytegaurav** [comment]
Can not reproduce this. Please check https://play.golang.org/p/4kB1ygWwhfz

**Comment by jrapoport** [comment]
yeah idk, i thought it was weird at the time and now can't repro either. 🤷🏻‍♂️
