### ISSUE TITLE
Publish a new release please!

### ISSUE THREAD

**Issue by wuhan005** [json-iterator/go#536]
The issue https://github.com/json-iterator/go/issues/469 has been fixed in https://github.com/json-iterator/go/commit/5bce16d299eb21bb5a80aa37151d805c37acd79d on 21 Jul 2020. 

However, the latest release is published on 9 Jun 2020, so developers will still get the bug version by `go get github.com/json-iterator/go` command.

Please publish a new release to fix this problem, thanks.

**Comment by AllenX2018** [comment]
done
