### ISSUE TITLE
marshalled results not sorted same as stdlib

### ISSUE THREAD

**Issue by thockin** [json-iterator/go#54]
```
	json_test.go:29: marshal expected:
		    {
		    >  "-1538202063": 0.3634222946643717,
		    >  "1223101607": 0.16867633434109314,
		    >  "576443938": 0.020297602318735935
		    }
		got:
		    {
		    >  "576443938": 0.020297602318735935,
		    >  "1223101607": 0.16867633434109314,
		    >  "-1538202063": 0.3634222946643717
		    }
```

This is sort of tedious, but being exactly compatible has some value, right?

**Comment by taowen** [comment]
JSON does not require the key to be sorted. I would like to treat the two representation to be equivalent. If there is other user vote for this feature, I might support it.

**Comment by thockin** [comment]
2 arguments:

1) it makes the test less useful
2) systems like kubernetes want to be able to diff file-saved JSON and server-saved JSON, and this makes it impossible.

**Comment by taowen** [comment]
as this will cause significant cost to user not requiring it. sorting should be an optional behavior.

**Comment by thockin** [comment]
I think it might be a good design to have something like a policy type that
carries config values, and let encode/decode use those.  That way users can
measure and make tradeoffs.

E.g., `spew` does this:

```
spew.Printf(fmt, obj) // uses default config

x := spew.ConfigState{ SpewKeys: true }
x..Printf(fmt, obj) // uses custom config
```

so this could be:

```
json := jsoniter.Config { SortMaps: true, HTMLEscape: true }
jb, err := json.Marshal(obj)
```

and you could offer a `StdlibConfig` pkg variable that was exactly Golang
compatible, but not fast and a `Fast` variable that wasn't compatible but
used all optimizations.

Though, hopefully the compatible version can be fast, otherwise why not
just use the Golang impl ? :)

**Comment by taowen** [comment]
I am sure most user do not need to sort the map keys, and do not know std impl actually sorts the map keys. Taking things out of the std impl to make it faster while still keeping the behavior "compatible" is the goal. To be fair, std impl does the validation much more strictly, and many other things. But not everybody is happy with the fact those many other things come with runtime penalty. 

I like 

```
json := jsoniter.Config { SortMaps: true, HTMLEscape: true }
jb, err := json.Marshal(obj)
```

**Comment by thockin** [comment]
Yeah, leaving that to the user sounds good, even if not default.  I will
watch repo for changes, and send more test cases.

**Comment by taowen** [comment]
@thockin it is supported now
