### ISSUE TITLE
json marshal panic

### ISSUE THREAD

**Issue by yuanhengL** [json-iterator/go#592]
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x60aa5b]

goroutine 175339137 [running]:
runtime.throw(0xe9655e, 0x5)
	/home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/go-env/go1-15-linux-amd64/src/runtime/panic.go:1116 +0x72 fp=0xc01104eaa8 sp=0xc01104ea78 pc=0x43c6d2
runtime.sigpanic()
	/home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/go-env/go1-15-linux-amd64/src/runtime/signal_unix.go:749 +0x405 fp=0xc01104ead8 sp=0xc01104eaa8 pc=0x452ca5
github.com/json-iterator/go.(*Stream).WriteStringWithHTMLEscaped(0xc01713f6e0, 0x784e6936384f3246, 0x7443454a5a426b63)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/stream_str.go:227 +0x7b fp=0xc01104eb40 sp=0xc01104ead8 pc=0x60aa5b
github.com/json-iterator/go.(*htmlEscapedStringEncoder).Encode(0x157eb70, 0xc013026008, 0xc01713f6e0)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:263 +0x45 fp=0xc01104eb68 sp=0xc01104eb40 pc=0x5dede5
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc014943710, 0xc017478088, 0xc019635f20)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:299 +0x275 fp=0xc01104ecd0 sp=0xc01104eb68 pc=0x5f42f5
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc014958c30, 0xc012ebd860, 0xc019635f20)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x68 fp=0xc01104ecf8 sp=0xc01104ecd0 pc=0x5eb108
github.com/json-iterator/go.(*Stream).WriteVal(0xc019635f20, 0xd6b860, 0xc012ebd860)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc01104ed60 sp=0xc01104ecf8 pc=0x5e9f90
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc014958c20, 0xc012f820b8, 0xc019635f20)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_dynamic.go:15 +0x65 fp=0xc01104ed90 sp=0xc01104ed60 pc=0x5ecd65
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc014943710, 0xc017478080, 0xc016d00c60)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:311 +0x3e8 fp=0xc01104eef8 sp=0xc01104ed90 pc=0x5f4468
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc014958c30, 0xc012ebd830, 0xc016d00c60)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x68 fp=0xc01104ef20 sp=0xc01104eef8 pc=0x5eb108
github.com/json-iterator/go.(*Stream).WriteVal(0xc016d00c60, 0xd6b860, 0xc012ebd830)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc01104ef88 sp=0xc01104ef20 pc=0x5e9f90
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc014958df0, 0xc0175fc370, 0xc016d00c60)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_dynamic.go:15 +0x65 fp=0xc01104efb8 sp=0xc01104ef88 pc=0x5ecd65
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc014962300, 0xc012e699c0, 0xc016d00c60)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_slice.go:42 +0x15b fp=0xc01104f040 sp=0xc01104efb8 pc=0x5fadfb
github.com/json-iterator/go.(*Stream).WriteVal(0xc016d00c60, 0xd18300, 0xc012e699c0)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc01104f0a8 sp=0xc01104f040 pc=0x5e9f90
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc014958c20, 0xc011cc0778, 0xc016d00c60)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_dynamic.go:15 +0x65 fp=0xc01104f0d8 sp=0xc01104f0a8 pc=0x5ecd65
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc014943710, 0xc00d923cb8, 0xc01c318840)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:311 +0x3e8 fp=0xc01104f240 sp=0xc01104f0d8 pc=0x5f4468
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc014958c30, 0xc012ebc330, 0xc01c318840)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x68 fp=0xc01104f268 sp=0xc01104f240 pc=0x5eb108
github.com/json-iterator/go.(*Stream).WriteVal(0xc01c318840, 0xd6b860, 0xc012ebc330)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc01104f2d0 sp=0xc01104f268 pc=0x5e9f90
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc014958c20, 0xc012fa6088, 0xc01c318840)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_dynamic.go:15 +0x65 fp=0xc01104f300 sp=0xc01104f2d0 pc=0x5ecd65
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc014943710, 0xc00d923cb0, 0xc01a4f1500)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:311 +0x3e8 fp=0xc01104f468 sp=0xc01104f300 pc=0x5f4468
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc014958c30, 0xc012ebc300, 0xc01a4f1500)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x68 fp=0xc01104f490 sp=0xc01104f468 pc=0x5eb108
github.com/json-iterator/go.(*Stream).WriteVal(0xc01a4f1500, 0xd6b860, 0xc012ebc300)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc01104f4f8 sp=0xc01104f490 pc=0x5e9f90
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc014958c20, 0xc012e1ff18, 0xc01a4f1500)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_dynamic.go:15 +0x65 fp=0xc01104f528 sp=0xc01104f4f8 pc=0x5ecd65
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc014943710, 0xc00d923ca0, 0xc01ed89860)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:311 +0x3e8 fp=0xc01104f690 sp=0xc01104f528 pc=0x5f4468
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc014958c30, 0xc012ebc2a0, 0xc01ed89860)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x68 fp=0xc01104f6b8 sp=0xc01104f690 pc=0x5eb108
github.com/json-iterator/go.(*Stream).WriteVal(0xc01ed89860, 0xd6b860, 0xc012ebc2a0)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc01104f720 sp=0xc01104f6b8 pc=0x5e9f90
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc014958d40, 0xc012f83dc8, 0xc01ed89860)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_dynamic.go:15 +0x65 fp=0xc01104f750 sp=0xc01104f720 pc=0x5ecd65
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc014943950, 0xc00d923968, 0xc019481800)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:311 +0x3e8 fp=0xc01104f8b8 sp=0xc01104f750 pc=0x5f4468
github.com/json-iterator/go.(*sliceEncoder).Encode(0xc014962180, 0xc012e69a60, 0xc019481800)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_slice.go:38 +0xef fp=0xc01104f940 sp=0xc01104f8b8 pc=0x5fad8f
github.com/json-iterator/go.(*Stream).WriteVal(0xc019481800, 0xd18740, 0xc012e69a60)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc01104f9a8 sp=0xc01104f940 pc=0x5e9f90
github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc014958c20, 0xc012fa92d8, 0xc019481800)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_dynamic.go:15 +0x65 fp=0xc01104f9d8 sp=0xc01104f9a8 pc=0x5ecd65
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc014943710, 0xc00d923970, 0xc016d01380)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:311 +0x3e8 fp=0xc01104fb40 sp=0xc01104f9d8 pc=0x5f4468
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc014958c30, 0xc012fa48d0, 0xc016d01380)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x68 fp=0xc01104fb68 sp=0xc01104fb40 pc=0x5eb108
github.com/json-iterator/go.(*Stream).WriteVal(0xc016d01380, 0xd6b860, 0xc012fa48d0)
	/home/ferry/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x150 fp=0xc01104fbd0 sp=0xc01104fb68 pc=0x5e9f90

when use this code:
![image](https://user-images.githubusercontent.com/88923662/144020244-8cfdd3fb-6dad-454e-833a-b4337f2fdff9.png)

**Comment by liqiongfan** [comment]
要使用 ConfigFastest模式，不要使用ConfigCompatibleWithStandardLibrary模式
stream := jsoniter.ConfigFastest.BorrowStream(nil)
jsoniter.ConfigFastest.ReturnStream(stream)
stream.WriteVal(b)
os.Stdout.Write(stream.Buffer())

**Comment by Mvbbb** [comment]
> 

使用 ConfigCompatibleWithStandardLibrary 相较于 ConfigFastest 有什么副作用吗
