### ISSUE TITLE
arm linux support

### ISSUE THREAD

**Issue by qianxiansheng90** [json-iterator/go#614]
env:
hardware:mac studio
system:ubuntu-20.04.4-live-server-arm64
go version go1.18 linux/arm64

code:
`
package main

import (
	"encoding/json"
	"fmt"

	jsoniter "github.com/json-iterator/go"
)

type T struct {
	ID   int         `json:"id"`
	Msg  string      `json:"msg"`
	Body interface{} `json:"body"`
}
type M struct {
	ID  int    `json:"id"`
	Msg string `json:"msg"`
}

func main() {
	var data = T{
		ID:  1,
		Msg: "123",
		Body: M{
			ID:  2,
			Msg: "456",
		},
	}
	var data2 T
	var dataJson, bodyJson []byte
	var body M
	var err error
	if dataJson, err = json.Marshal(data); err != nil {
		fmt.Println(err)
		return
	}
	if err = jsoniter.Unmarshal(dataJson, &data2); err != nil {
		fmt.Println(err)
		return
	}

	if bodyJson, err = jsoniter.Marshal(data2.Body); err != nil {
		fmt.Println(err)
		return
	}
	if err = jsoniter.Unmarshal(bodyJson, &body); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(body)
}

`

error:
unexpected fault address 0x808085a175a75
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x808085a175a75 pc=0x6b450]

goroutine 1 [running]:
runtime.throw({0x132df2?, 0x7231c?})
	/usr/local/go/src/runtime/panic.go:992 +0x50 fp=0x4000045b30 sp=0x4000045b00 pc=0x40c90
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x1a4 fp=0x4000045b60 sp=0x4000045b30 pc=0x57154
aeshashbody()
	/usr/local/go/src/runtime/asm_arm64.s:874 +0x2d0 fp=0x4000045b70 sp=0x4000045b70 pc=0x6b450
runtime.mapiternext(0x400007c540)
	/usr/local/go/src/runtime/map.go:934 +0x2c4 fp=0x4000045be0 sp=0x4000045b70 pc=0x1d874
runtime.mapiterinit(0x112320?, 0x400006dc80?, 0x4000010ef0?)
	/usr/local/go/src/runtime/map.go:861 +0x2f4 fp=0x4000045c10 sp=0x4000045be0 pc=0x1d574
reflect.mapiterinit(0x0?, 0x400006ced8?, 0x4000045cc8?)
	/usr/local/go/src/runtime/map.go:1373 +0x20 fp=0x4000045c40 sp=0x4000045c10 pc=0x692d0
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/home/qfy/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*mapEncoder).Encode(0x400006dc50, 0x400000e320, 0x4000056180)
	/home/qfy/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:257 +0x238 fp=0x4000045d00 sp=0x4000045c40 pc=0xe3aa8
github.com/json-iterator/go.(*onePtrEncoder).Encode(0x4000010ed0, 0x400006da40, 0x400007c540?)
	/home/qfy/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x8c fp=0x4000045d40 sp=0x4000045d00 pc=0xdca5c
github.com/json-iterator/go.(*Stream).WriteVal(0x4000056180, {0x112800, 0x400006da40})
	/home/qfy/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x174 fp=0x4000045dc0 sp=0x4000045d40 pc=0xdbe14
github.com/json-iterator/go.(*frozenConfig).Marshal(0x4000106000, {0x112800, 0x400006da40})
	/home/qfy/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0x88 fp=0x4000045e60 sp=0x4000045dc0 pc=0xd4308
github.com/json-iterator/go.Marshal(...)
	/home/qfy/go/pkg/mod/github.com/json-iterator/go@v1.1.11/adapter.go:34
main.main()
	/media/psf/code/dubai_server/test_json.go:51 +0x1f4 fp=0x4000045f70 sp=0x4000045e60 pc=0xf9c14
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x258 fp=0x4000045fd0 sp=0x4000045f70 pc=0x43268
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1259 +0x4 fp=0x4000045fd0 sp=0x4000045fd0 pc=0x6ddc4
exit status 2

**Comment by taowen** [comment]
https://github.com/json-iterator/go/releases/tag/v1.1.12

**Comment by qianxiansheng90** [comment]
Highly efficient
