### ISSUE TITLE
Concurrent Unmarshal causes segmentation violation

### ISSUE THREAD

**Issue by klaubert** [json-iterator/go#65]
Hi, 
I just try jsoniter as replacement for json, and in a concurrent code jsoniter produce a segmentation violation. With one go routine its ok (and very fast).
With json library, concurrent code works fine.

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4b4249]

goroutine 6 [running]:
github.com/json-iterator/go.(*placeholderDecoder).decode(0xc42000e350, 0xc42012e000, 0xc420130000)
        /home/klaubert/projetos/gocode/src/github.com/json-iterator/go/feature_reflect.go:190 +0x29
github.com/json-iterator/go.(*Iterator).ReadVal(0xc420130000, 0x4e3640, 0xc42012e000)
        /home/klaubert/projetos/gocode/src/github.com/json-iterator/go/feature_reflect.go:228 +0xb9
```
Basically a `jsoniter.Unmarshal(fh, &e)` is used...

Any comment regard the concurrent usage of jsoniter.Unmarshal?

**Comment by taowen** [comment]
should be fixed

**Comment by klaubert** [comment]
Fixed, very fast fix, thank you very much.
Very linear response when using concurrently. 3 to 5 time faster than native json .
