### ISSUE TITLE
Unmarshalling anonymous/embedded fields

### ISSUE THREAD

**Issue by lnquy** [json-iterator/go#85]
Hi @taowen ,
Thanks for the great project.
I tried the jsoniter and was impressed by its simplicity and performance.
But I notice that jsoniter silently ignores the anonymous/embedded fields.
I tried to take a look on the project's issues and document but still can find anywhere you say about it.
Please help me to confirm that is there any way to unmarshal anonymous/embedded fields by jsoniter or not?
If not, I think you should provide a quick note on README file.
Thanks.

**Comment by taowen** [comment]
Jsoniter keep the behavior same as the standard library, so documentation is not a priority.

If you believe, the behavior "silently ignores the anonymous/embedded fields" is not the same as standard library. Please provide an example, I will fix it.

**Comment by lnquy** [comment]
Hi @taowen,
Please take a look on this example: https://play.golang.org/p/NX3e5JEYh0

**Comment by taowen** [comment]
fixed
